// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO rp.attachments (
  work_order_id, phase, original_filename, mime_type, size_bytes,
  storage_path, width, height, uploaded_by_user_id, created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $9)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, work_order_id, phase, original_filename, mime_type, size_bytes, storage_path, width, height, uploaded_by_user_id
`

type CreateAttachmentParams struct {
	WorkOrderID      int64       `json:"work_order_id"`
	Phase            string      `json:"phase"`
	OriginalFilename string      `json:"original_filename"`
	MimeType         string      `json:"mime_type"`
	SizeBytes        int64       `json:"size_bytes"`
	StoragePath      string      `json:"storage_path"`
	Width            pgtype.Int4 `json:"width"`
	Height           pgtype.Int4 `json:"height"`
	UploadedByUserID pgtype.Int8 `json:"uploaded_by_user_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.WorkOrderID,
		arg.Phase,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.Width,
		arg.Height,
		arg.UploadedByUserID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WorkOrderID,
		&i.Phase,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.Width,
		&i.Height,
		&i.UploadedByUserID,
	)
	return i, err
}

const getAttachmentByUcode = `-- name: GetAttachmentByUcode :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, work_order_id, phase, original_filename, mime_type, size_bytes, storage_path, width, height, uploaded_by_user_id FROM rp.attachments
WHERE ucode = $1 AND voided_ts IS NULL
`

func (q *Queries) GetAttachmentByUcode(ctx context.Context, ucode pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByUcode, ucode)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WorkOrderID,
		&i.Phase,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.Width,
		&i.Height,
		&i.UploadedByUserID,
	)
	return i, err
}

const listWorkOrderAttachments = `-- name: ListWorkOrderAttachments :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, work_order_id, phase, original_filename, mime_type, size_bytes, storage_path, width, height, uploaded_by_user_id FROM rp.attachments
WHERE work_order_id = $1 AND voided_ts IS NULL
ORDER BY created_ts ASC, id ASC
`

func (q *Queries) ListWorkOrderAttachments(ctx context.Context, workOrderID int64) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listWorkOrderAttachments, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.WorkOrderID,
			&i.Phase,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.Width,
			&i.Height,
			&i.UploadedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :exec
UPDATE rp.attachments SET voided_ts = now(), voided_by_user_id = $2
WHERE id = $1 AND voided_ts IS NULL
`

type SoftDeleteAttachmentParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteAttachment(ctx context.Context, arg SoftDeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, softDeleteAttachment, arg.ID, arg.VoidedByUserID)
	return err
}
