// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditEntries = `-- name: CountAuditEntries :one
SELECT count(*)::bigint
FROM rp.audit_log a
WHERE
      (NOT $1::bool   OR a.actor_user_id = $2::bigint)
  AND ($3::text = '' OR a.entity_type   = $3::text)
  AND (NOT $4::bool OR a.entity_ucode = $5::uuid)
  AND ($6::text      = '' OR a.action        = $6::text)
  AND (NOT $7::bool OR a.created_ts >= $8::timestamptz)
  AND (NOT $9::bool   OR a.created_ts <= $10::timestamptz)
`

type CountAuditEntriesParams struct {
	HasActor       bool               `json:"has_actor"`
	ActorUserID    int64              `json:"actor_user_id"`
	EntityType     string             `json:"entity_type"`
	HasEntityUcode bool               `json:"has_entity_ucode"`
	EntityUcode    pgtype.UUID        `json:"entity_ucode"`
	Action         string             `json:"action"`
	HasFrom        bool               `json:"has_from"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	HasTo          bool               `json:"has_to"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
}

func (q *Queries) CountAuditEntries(ctx context.Context, arg CountAuditEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEntries,
		arg.HasActor,
		arg.ActorUserID,
		arg.EntityType,
		arg.HasEntityUcode,
		arg.EntityUcode,
		arg.Action,
		arg.HasFrom,
		arg.DateFrom,
		arg.HasTo,
		arg.DateTo,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAuditEntry = `-- name: CreateAuditEntry :one
INSERT INTO rp.audit_log (
  actor_user_id, action, entity_type, entity_id, entity_ucode,
  before_json, after_json, ip, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, ucode, created_ts, actor_user_id, action, entity_type, entity_id, entity_ucode, before_json, after_json, ip, user_agent
`

type CreateAuditEntryParams struct {
	ActorUserID pgtype.Int8 `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.Int8 `json:"entity_id"`
	EntityUcode pgtype.UUID `json:"entity_ucode"`
	BeforeJson  []byte      `json:"before_json"`
	AfterJson   []byte      `json:"after_json"`
	Ip          pgtype.Text `json:"ip"`
	UserAgent   pgtype.Text `json:"user_agent"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditEntry,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.EntityUcode,
		arg.BeforeJson,
		arg.AfterJson,
		arg.Ip,
		arg.UserAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.ActorUserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.EntityUcode,
		&i.BeforeJson,
		&i.AfterJson,
		&i.Ip,
		&i.UserAgent,
	)
	return i, err
}

const listAuditEntries = `-- name: ListAuditEntries :many
SELECT
  a.id, a.ucode, a.created_ts, a.actor_user_id, a.action, a.entity_type, a.entity_id, a.entity_ucode, a.before_json, a.after_json, a.ip, a.user_agent,
  u.username  AS actor_username,
  u.full_name AS actor_full_name
FROM rp.audit_log a
LEFT JOIN rp.users u ON u.id = a.actor_user_id
WHERE
      (NOT $1::bool   OR a.actor_user_id = $2::bigint)
  AND ($3::text = '' OR a.entity_type   = $3::text)
  AND (NOT $4::bool OR a.entity_ucode = $5::uuid)
  AND ($6::text      = '' OR a.action        = $6::text)
  AND (NOT $7::bool OR a.created_ts >= $8::timestamptz)
  AND (NOT $9::bool   OR a.created_ts <= $10::timestamptz)
ORDER BY a.created_ts DESC, a.id DESC
LIMIT $12::int OFFSET $11::int
`

type ListAuditEntriesParams struct {
	HasActor       bool               `json:"has_actor"`
	ActorUserID    int64              `json:"actor_user_id"`
	EntityType     string             `json:"entity_type"`
	HasEntityUcode bool               `json:"has_entity_ucode"`
	EntityUcode    pgtype.UUID        `json:"entity_ucode"`
	Action         string             `json:"action"`
	HasFrom        bool               `json:"has_from"`
	DateFrom       pgtype.Timestamptz `json:"date_from"`
	HasTo          bool               `json:"has_to"`
	DateTo         pgtype.Timestamptz `json:"date_to"`
	PageOffset     int32              `json:"page_offset"`
	PageSize       int32              `json:"page_size"`
}

type ListAuditEntriesRow struct {
	AuditLog      AuditLog    `json:"audit_log"`
	ActorUsername pgtype.Text `json:"actor_username"`
	ActorFullName pgtype.Text `json:"actor_full_name"`
}

func (q *Queries) ListAuditEntries(ctx context.Context, arg ListAuditEntriesParams) ([]ListAuditEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAuditEntries,
		arg.HasActor,
		arg.ActorUserID,
		arg.EntityType,
		arg.HasEntityUcode,
		arg.EntityUcode,
		arg.Action,
		arg.HasFrom,
		arg.DateFrom,
		arg.HasTo,
		arg.DateTo,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEntriesRow{}
	for rows.Next() {
		var i ListAuditEntriesRow
		if err := rows.Scan(
			&i.AuditLog.ID,
			&i.AuditLog.Ucode,
			&i.AuditLog.CreatedTs,
			&i.AuditLog.ActorUserID,
			&i.AuditLog.Action,
			&i.AuditLog.EntityType,
			&i.AuditLog.EntityID,
			&i.AuditLog.EntityUcode,
			&i.AuditLog.BeforeJson,
			&i.AuditLog.AfterJson,
			&i.AuditLog.Ip,
			&i.AuditLog.UserAgent,
			&i.ActorUsername,
			&i.ActorFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
