// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClients = `-- name: CountClients :one
SELECT count(*)::bigint
FROM rp.clients
WHERE voided_ts IS NULL
  AND (
    $1::text = ''
    OR search @@ plainto_tsquery('spanish', $1::text)
    OR lower(name) LIKE lower('%' || $1::text || '%')
    OR phone = $1::text
  )
`

func (q *Queries) CountClients(ctx context.Context, q_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countClients, q_)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO rp.clients (
  name,
  phone,
  email,
  dni_cuit,
  address,
  notes,
  client_type,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, dni_cuit, address, notes, client_type, search
`

type CreateClientParams struct {
	Name            string      `json:"name"`
	Phone           pgtype.Text `json:"phone"`
	Email           pgtype.Text `json:"email"`
	DniCuit         pgtype.Text `json:"dni_cuit"`
	Address         pgtype.Text `json:"address"`
	Notes           pgtype.Text `json:"notes"`
	ClientType      string      `json:"client_type"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.DniCuit,
		arg.Address,
		arg.Notes,
		arg.ClientType,
		arg.CreatedByUserID,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.DniCuit,
		&i.Address,
		&i.Notes,
		&i.ClientType,
		&i.Search,
	)
	return i, err
}

const getClientByPhone = `-- name: GetClientByPhone :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, dni_cuit, address, notes, client_type, search
FROM rp.clients
WHERE phone = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetClientByPhone(ctx context.Context, phone pgtype.Text) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByPhone, phone)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.DniCuit,
		&i.Address,
		&i.Notes,
		&i.ClientType,
		&i.Search,
	)
	return i, err
}

const getClientByUcode = `-- name: GetClientByUcode :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, dni_cuit, address, notes, client_type, search
FROM rp.clients
WHERE ucode = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetClientByUcode(ctx context.Context, ucode pgtype.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByUcode, ucode)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.DniCuit,
		&i.Address,
		&i.Notes,
		&i.ClientType,
		&i.Search,
	)
	return i, err
}

const listClientDevices = `-- name: ListClientDevices :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, client_id, brand_id, model_id, article_type_id, serial_number, color, description
FROM rp.devices
WHERE client_id = $1
  AND voided_ts IS NULL
ORDER BY created_ts DESC
`

func (q *Queries) ListClientDevices(ctx context.Context, clientID int64) ([]Device, error) {
	rows, err := q.db.Query(ctx, listClientDevices, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.ClientID,
			&i.BrandID,
			&i.ModelID,
			&i.ArticleTypeID,
			&i.SerialNumber,
			&i.Color,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchClients = `-- name: SearchClients :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, dni_cuit, address, notes, client_type, search
FROM rp.clients
WHERE voided_ts IS NULL
  AND (
    $1::text = ''
    OR search @@ plainto_tsquery('spanish', $1::text)
    OR lower(name) LIKE lower('%' || $1::text || '%')
    OR phone = $1::text
  )
ORDER BY name ASC
LIMIT $3::int OFFSET $2::int
`

type SearchClientsParams struct {
	Q          string `json:"q"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) SearchClients(ctx context.Context, arg SearchClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, searchClients, arg.Q, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.DniCuit,
			&i.Address,
			&i.Notes,
			&i.ClientType,
			&i.Search,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteClient = `-- name: SoftDeleteClient :exec
UPDATE rp.clients
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type SoftDeleteClientParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteClient(ctx context.Context, arg SoftDeleteClientParams) error {
	_, err := q.db.Exec(ctx, softDeleteClient, arg.ID, arg.VoidedByUserID)
	return err
}

const updateClient = `-- name: UpdateClient :one
UPDATE rp.clients
SET
  name = $2,
  phone = $3,
  email = $4,
  dni_cuit = $5,
  address = $6,
  notes = $7,
  client_type = $8
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, dni_cuit, address, notes, client_type, search
`

type UpdateClientParams struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Phone      pgtype.Text `json:"phone"`
	Email      pgtype.Text `json:"email"`
	DniCuit    pgtype.Text `json:"dni_cuit"`
	Address    pgtype.Text `json:"address"`
	Notes      pgtype.Text `json:"notes"`
	ClientType string      `json:"client_type"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.DniCuit,
		arg.Address,
		arg.Notes,
		arg.ClientType,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.DniCuit,
		&i.Address,
		&i.Notes,
		&i.ClientType,
		&i.Search,
	)
	return i, err
}
