// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO rp.devices (
  client_id,
  brand_id,
  model_id,
  article_type_id,
  serial_number,
  color,
  description,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, client_id, brand_id, model_id, article_type_id, serial_number, color, description
`

type CreateDeviceParams struct {
	ClientID        int64       `json:"client_id"`
	BrandID         int64       `json:"brand_id"`
	ModelID         pgtype.Int8 `json:"model_id"`
	ArticleTypeID   int64       `json:"article_type_id"`
	SerialNumber    pgtype.Text `json:"serial_number"`
	Color           pgtype.Text `json:"color"`
	Description     pgtype.Text `json:"description"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ClientID,
		arg.BrandID,
		arg.ModelID,
		arg.ArticleTypeID,
		arg.SerialNumber,
		arg.Color,
		arg.Description,
		arg.CreatedByUserID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.ClientID,
		&i.BrandID,
		&i.ModelID,
		&i.ArticleTypeID,
		&i.SerialNumber,
		&i.Color,
		&i.Description,
	)
	return i, err
}

const getDeviceByUcode = `-- name: GetDeviceByUcode :one
SELECT
  d.id, d.ucode, d.created_ts, d.created_by_user_id, d.voided_ts, d.voided_by_user_id, d.client_id, d.brand_id, d.model_id, d.article_type_id, d.serial_number, d.color, d.description,
  c.ucode AS client_ucode,
  b.ucode AS brand_ucode,
  dm.ucode AS model_ucode,
  at.ucode AS article_type_ucode
FROM rp.devices d
JOIN rp.clients c ON c.id = d.client_id
JOIN rp.brands b ON b.id = d.brand_id
LEFT JOIN rp.device_models dm ON dm.id = d.model_id
JOIN rp.article_types at ON at.id = d.article_type_id
WHERE d.ucode = $1
  AND d.voided_ts IS NULL
`

type GetDeviceByUcodeRow struct {
	Device           Device      `json:"device"`
	ClientUcode      pgtype.UUID `json:"client_ucode"`
	BrandUcode       pgtype.UUID `json:"brand_ucode"`
	ModelUcode       pgtype.UUID `json:"model_ucode"`
	ArticleTypeUcode pgtype.UUID `json:"article_type_ucode"`
}

func (q *Queries) GetDeviceByUcode(ctx context.Context, ucode pgtype.UUID) (GetDeviceByUcodeRow, error) {
	row := q.db.QueryRow(ctx, getDeviceByUcode, ucode)
	var i GetDeviceByUcodeRow
	err := row.Scan(
		&i.Device.ID,
		&i.Device.Ucode,
		&i.Device.CreatedTs,
		&i.Device.CreatedByUserID,
		&i.Device.VoidedTs,
		&i.Device.VoidedByUserID,
		&i.Device.ClientID,
		&i.Device.BrandID,
		&i.Device.ModelID,
		&i.Device.ArticleTypeID,
		&i.Device.SerialNumber,
		&i.Device.Color,
		&i.Device.Description,
		&i.ClientUcode,
		&i.BrandUcode,
		&i.ModelUcode,
		&i.ArticleTypeUcode,
	)
	return i, err
}

const searchDevices = `-- name: SearchDevices :many
SELECT
  d.id, d.ucode, d.created_ts, d.created_by_user_id, d.voided_ts, d.voided_by_user_id, d.client_id, d.brand_id, d.model_id, d.article_type_id, d.serial_number, d.color, d.description,
  c.ucode AS client_ucode,
  b.ucode AS brand_ucode,
  dm.ucode AS model_ucode,
  at.ucode AS article_type_ucode
FROM rp.devices d
JOIN rp.clients c ON c.id = d.client_id
JOIN rp.brands b ON b.id = d.brand_id
LEFT JOIN rp.device_models dm ON dm.id = d.model_id
JOIN rp.article_types at ON at.id = d.article_type_id
WHERE d.voided_ts IS NULL
  AND (NOT $1::bool OR d.client_id = $2::bigint)
  AND ($3::text = '' OR d.serial_number ILIKE $3::text || '%')
ORDER BY d.created_ts DESC
LIMIT 50
`

type SearchDevicesParams struct {
	HasClient bool   `json:"has_client"`
	ClientID  int64  `json:"client_id"`
	Serial    string `json:"serial"`
}

type SearchDevicesRow struct {
	Device           Device      `json:"device"`
	ClientUcode      pgtype.UUID `json:"client_ucode"`
	BrandUcode       pgtype.UUID `json:"brand_ucode"`
	ModelUcode       pgtype.UUID `json:"model_ucode"`
	ArticleTypeUcode pgtype.UUID `json:"article_type_ucode"`
}

func (q *Queries) SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]SearchDevicesRow, error) {
	rows, err := q.db.Query(ctx, searchDevices, arg.HasClient, arg.ClientID, arg.Serial)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDevicesRow{}
	for rows.Next() {
		var i SearchDevicesRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.Ucode,
			&i.Device.CreatedTs,
			&i.Device.CreatedByUserID,
			&i.Device.VoidedTs,
			&i.Device.VoidedByUserID,
			&i.Device.ClientID,
			&i.Device.BrandID,
			&i.Device.ModelID,
			&i.Device.ArticleTypeID,
			&i.Device.SerialNumber,
			&i.Device.Color,
			&i.Device.Description,
			&i.ClientUcode,
			&i.BrandUcode,
			&i.ModelUcode,
			&i.ArticleTypeUcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDevice = `-- name: SoftDeleteDevice :exec
UPDATE rp.devices
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type SoftDeleteDeviceParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, softDeleteDevice, arg.ID, arg.VoidedByUserID)
	return err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE rp.devices
SET
  client_id = $2,
  brand_id = $3,
  model_id = $4,
  article_type_id = $5,
  serial_number = $6,
  color = $7,
  description = $8
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, client_id, brand_id, model_id, article_type_id, serial_number, color, description
`

type UpdateDeviceParams struct {
	ID            int64       `json:"id"`
	ClientID      int64       `json:"client_id"`
	BrandID       int64       `json:"brand_id"`
	ModelID       pgtype.Int8 `json:"model_id"`
	ArticleTypeID int64       `json:"article_type_id"`
	SerialNumber  pgtype.Text `json:"serial_number"`
	Color         pgtype.Text `json:"color"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.ClientID,
		arg.BrandID,
		arg.ModelID,
		arg.ArticleTypeID,
		arg.SerialNumber,
		arg.Color,
		arg.Description,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.ClientID,
		&i.BrandID,
		&i.ModelID,
		&i.ArticleTypeID,
		&i.SerialNumber,
		&i.Color,
		&i.Description,
	)
	return i, err
}
