// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lookups.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArticleType = `-- name: CreateArticleType :one
INSERT INTO rp.article_types (name, created_by_user_id)
VALUES ($1, $2)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
`

type CreateArticleTypeParams struct {
	Name            string      `json:"name"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateArticleType(ctx context.Context, arg CreateArticleTypeParams) (ArticleType, error) {
	row := q.db.QueryRow(ctx, createArticleType, arg.Name, arg.CreatedByUserID)
	var i ArticleType
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
	)
	return i, err
}

const createBrand = `-- name: CreateBrand :one
INSERT INTO rp.brands (name, created_by_user_id)
VALUES ($1, $2)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
`

type CreateBrandParams struct {
	Name            string      `json:"name"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand, arg.Name, arg.CreatedByUserID)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
	)
	return i, err
}

const createDeviceModel = `-- name: CreateDeviceModel :one
INSERT INTO rp.device_models (brand_id, name, created_by_user_id)
VALUES ($1, $2, $3)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, brand_id, name
`

type CreateDeviceModelParams struct {
	BrandID         int64       `json:"brand_id"`
	Name            string      `json:"name"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateDeviceModel(ctx context.Context, arg CreateDeviceModelParams) (DeviceModel, error) {
	row := q.db.QueryRow(ctx, createDeviceModel, arg.BrandID, arg.Name, arg.CreatedByUserID)
	var i DeviceModel
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.BrandID,
		&i.Name,
	)
	return i, err
}

const getArticleTypeByUcode = `-- name: GetArticleTypeByUcode :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
FROM rp.article_types
WHERE ucode = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetArticleTypeByUcode(ctx context.Context, ucode pgtype.UUID) (ArticleType, error) {
	row := q.db.QueryRow(ctx, getArticleTypeByUcode, ucode)
	var i ArticleType
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
	)
	return i, err
}

const getBrandByUcode = `-- name: GetBrandByUcode :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
FROM rp.brands
WHERE ucode = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetBrandByUcode(ctx context.Context, ucode pgtype.UUID) (Brand, error) {
	row := q.db.QueryRow(ctx, getBrandByUcode, ucode)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
	)
	return i, err
}

const getDeviceModelByUcode = `-- name: GetDeviceModelByUcode :one
SELECT dm.id, dm.ucode, dm.created_ts, dm.created_by_user_id, dm.voided_ts, dm.voided_by_user_id, dm.brand_id, dm.name, b.ucode AS brand_ucode
FROM rp.device_models dm
JOIN rp.brands b ON b.id = dm.brand_id
WHERE dm.ucode = $1
  AND dm.voided_ts IS NULL
`

type GetDeviceModelByUcodeRow struct {
	DeviceModel DeviceModel `json:"device_model"`
	BrandUcode  pgtype.UUID `json:"brand_ucode"`
}

func (q *Queries) GetDeviceModelByUcode(ctx context.Context, ucode pgtype.UUID) (GetDeviceModelByUcodeRow, error) {
	row := q.db.QueryRow(ctx, getDeviceModelByUcode, ucode)
	var i GetDeviceModelByUcodeRow
	err := row.Scan(
		&i.DeviceModel.ID,
		&i.DeviceModel.Ucode,
		&i.DeviceModel.CreatedTs,
		&i.DeviceModel.CreatedByUserID,
		&i.DeviceModel.VoidedTs,
		&i.DeviceModel.VoidedByUserID,
		&i.DeviceModel.BrandID,
		&i.DeviceModel.Name,
		&i.BrandUcode,
	)
	return i, err
}

const listArticleTypes = `-- name: ListArticleTypes :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
FROM rp.article_types
WHERE voided_ts IS NULL
ORDER BY name
`

func (q *Queries) ListArticleTypes(ctx context.Context) ([]ArticleType, error) {
	rows, err := q.db.Query(ctx, listArticleTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArticleType{}
	for rows.Next() {
		var i ArticleType
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrands = `-- name: ListBrands :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
FROM rp.brands
WHERE voided_ts IS NULL
ORDER BY name
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.Query(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Brand{}
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceModelsByBrand = `-- name: ListDeviceModelsByBrand :many
SELECT dm.id, dm.ucode, dm.created_ts, dm.created_by_user_id, dm.voided_ts, dm.voided_by_user_id, dm.brand_id, dm.name, b.ucode AS brand_ucode
FROM rp.device_models dm
JOIN rp.brands b ON b.id = dm.brand_id
WHERE dm.brand_id = $1
  AND dm.voided_ts IS NULL
ORDER BY dm.name
`

type ListDeviceModelsByBrandRow struct {
	DeviceModel DeviceModel `json:"device_model"`
	BrandUcode  pgtype.UUID `json:"brand_ucode"`
}

func (q *Queries) ListDeviceModelsByBrand(ctx context.Context, brandID int64) ([]ListDeviceModelsByBrandRow, error) {
	rows, err := q.db.Query(ctx, listDeviceModelsByBrand, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceModelsByBrandRow{}
	for rows.Next() {
		var i ListDeviceModelsByBrandRow
		if err := rows.Scan(
			&i.DeviceModel.ID,
			&i.DeviceModel.Ucode,
			&i.DeviceModel.CreatedTs,
			&i.DeviceModel.CreatedByUserID,
			&i.DeviceModel.VoidedTs,
			&i.DeviceModel.VoidedByUserID,
			&i.DeviceModel.BrandID,
			&i.DeviceModel.Name,
			&i.BrandUcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteArticleType = `-- name: SoftDeleteArticleType :exec
UPDATE rp.article_types
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE ucode = $1
  AND voided_ts IS NULL
`

type SoftDeleteArticleTypeParams struct {
	Ucode          pgtype.UUID `json:"ucode"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteArticleType(ctx context.Context, arg SoftDeleteArticleTypeParams) error {
	_, err := q.db.Exec(ctx, softDeleteArticleType, arg.Ucode, arg.VoidedByUserID)
	return err
}

const softDeleteBrand = `-- name: SoftDeleteBrand :exec
UPDATE rp.brands
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE ucode = $1
  AND voided_ts IS NULL
`

type SoftDeleteBrandParams struct {
	Ucode          pgtype.UUID `json:"ucode"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteBrand(ctx context.Context, arg SoftDeleteBrandParams) error {
	_, err := q.db.Exec(ctx, softDeleteBrand, arg.Ucode, arg.VoidedByUserID)
	return err
}

const softDeleteDeviceModel = `-- name: SoftDeleteDeviceModel :exec
UPDATE rp.device_models
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE ucode = $1
  AND voided_ts IS NULL
`

type SoftDeleteDeviceModelParams struct {
	Ucode          pgtype.UUID `json:"ucode"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteDeviceModel(ctx context.Context, arg SoftDeleteDeviceModelParams) error {
	_, err := q.db.Exec(ctx, softDeleteDeviceModel, arg.Ucode, arg.VoidedByUserID)
	return err
}

const updateArticleType = `-- name: UpdateArticleType :one
UPDATE rp.article_types
SET name = $2
WHERE ucode = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
`

type UpdateArticleTypeParams struct {
	Ucode pgtype.UUID `json:"ucode"`
	Name  string      `json:"name"`
}

func (q *Queries) UpdateArticleType(ctx context.Context, arg UpdateArticleTypeParams) (ArticleType, error) {
	row := q.db.QueryRow(ctx, updateArticleType, arg.Ucode, arg.Name)
	var i ArticleType
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
	)
	return i, err
}

const updateBrand = `-- name: UpdateBrand :one
UPDATE rp.brands
SET name = $2
WHERE ucode = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name
`

type UpdateBrandParams struct {
	Ucode pgtype.UUID `json:"ucode"`
	Name  string      `json:"name"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, updateBrand, arg.Ucode, arg.Name)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
	)
	return i, err
}

const updateDeviceModel = `-- name: UpdateDeviceModel :one
UPDATE rp.device_models
SET name = $2
WHERE ucode = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, brand_id, name
`

type UpdateDeviceModelParams struct {
	Ucode pgtype.UUID `json:"ucode"`
	Name  string      `json:"name"`
}

func (q *Queries) UpdateDeviceModel(ctx context.Context, arg UpdateDeviceModelParams) (DeviceModel, error) {
	row := q.db.QueryRow(ctx, updateDeviceModel, arg.Ucode, arg.Name)
	var i DeviceModel
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.BrandID,
		&i.Name,
	)
	return i, err
}
