// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArticleType struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
}

type Brand struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
}

type Client struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
	Phone           pgtype.Text        `json:"phone"`
	Email           pgtype.Text        `json:"email"`
	DniCuit         pgtype.Text        `json:"dni_cuit"`
	Address         pgtype.Text        `json:"address"`
	Notes           pgtype.Text        `json:"notes"`
	ClientType      string             `json:"client_type"`
	Search          interface{}        `json:"search"`
}

type Device struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	ClientID        int64              `json:"client_id"`
	BrandID         int64              `json:"brand_id"`
	ModelID         pgtype.Int8        `json:"model_id"`
	ArticleTypeID   int64              `json:"article_type_id"`
	SerialNumber    pgtype.Text        `json:"serial_number"`
	Color           pgtype.Text        `json:"color"`
	Description     pgtype.Text        `json:"description"`
}

type DeviceModel struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	BrandID         int64              `json:"brand_id"`
	Name            string             `json:"name"`
}

type Session struct {
	ID         []byte             `json:"id"`
	UserID     int64              `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedTs pgtype.Timestamptz `json:"last_used_ts"`
	Ip         *netip.Addr        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedTs  pgtype.Timestamptz `json:"created_ts"`
}

type User struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	FullName        string             `json:"full_name"`
	Role            string             `json:"role"`
	LastLoginTs     pgtype.Timestamptz `json:"last_login_ts"`
}

type WoNumberCounter struct {
	Year    int32 `json:"year"`
	LastSeq int64 `json:"last_seq"`
}

type WorkOrder struct {
	ID                 int64              `json:"id"`
	Ucode              pgtype.UUID        `json:"ucode"`
	CreatedTs          pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID    pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs           pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID     pgtype.Int8        `json:"voided_by_user_id"`
	WoNumber           string             `json:"wo_number"`
	DeviceID           int64              `json:"device_id"`
	ClientID           int64              `json:"client_id"`
	ServiceType        string             `json:"service_type"`
	Status             string             `json:"status"`
	ReportedIssue      string             `json:"reported_issue"`
	Diagnosis          pgtype.Text        `json:"diagnosis"`
	QuoteAmount        pgtype.Numeric     `json:"quote_amount"`
	QuoteCurrency      string             `json:"quote_currency"`
	QuoteSentTs        pgtype.Timestamptz `json:"quote_sent_ts"`
	QuoteApprovedTs    pgtype.Timestamptz `json:"quote_approved_ts"`
	QuoteRejectedTs    pgtype.Timestamptz `json:"quote_rejected_ts"`
	FinalAmount        pgtype.Numeric     `json:"final_amount"`
	LaborAmount        pgtype.Numeric     `json:"labor_amount"`
	PartsAmount        pgtype.Numeric     `json:"parts_amount"`
	IntakeNotes        pgtype.Text        `json:"intake_notes"`
	Accessories        pgtype.Text        `json:"accessories"`
	DevicePinEncrypted pgtype.Text        `json:"device_pin_encrypted"`
	ReceivedTs         pgtype.Timestamptz `json:"received_ts"`
	StartedTs          pgtype.Timestamptz `json:"started_ts"`
	ReadyTs            pgtype.Timestamptz `json:"ready_ts"`
	DeliveredTs        pgtype.Timestamptz `json:"delivered_ts"`
	CancelledTs        pgtype.Timestamptz `json:"cancelled_ts"`
	CancelReason       pgtype.Text        `json:"cancel_reason"`
}
