// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ArticleType struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
}

type Attachment struct {
	ID               int64              `json:"id"`
	Ucode            pgtype.UUID        `json:"ucode"`
	CreatedTs        pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID  pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs         pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID   pgtype.Int8        `json:"voided_by_user_id"`
	WorkOrderID      int64              `json:"work_order_id"`
	Phase            string             `json:"phase"`
	OriginalFilename string             `json:"original_filename"`
	MimeType         string             `json:"mime_type"`
	SizeBytes        int64              `json:"size_bytes"`
	StoragePath      string             `json:"storage_path"`
	Width            pgtype.Int4        `json:"width"`
	Height           pgtype.Int4        `json:"height"`
	UploadedByUserID pgtype.Int8        `json:"uploaded_by_user_id"`
}

type AuditLog struct {
	ID          int64              `json:"id"`
	Ucode       pgtype.UUID        `json:"ucode"`
	CreatedTs   pgtype.Timestamptz `json:"created_ts"`
	ActorUserID pgtype.Int8        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Int8        `json:"entity_id"`
	EntityUcode pgtype.UUID        `json:"entity_ucode"`
	BeforeJson  []byte             `json:"before_json"`
	AfterJson   []byte             `json:"after_json"`
	Ip          pgtype.Text        `json:"ip"`
	UserAgent   pgtype.Text        `json:"user_agent"`
}

type Brand struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
}

type Client struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
	Phone           pgtype.Text        `json:"phone"`
	Email           pgtype.Text        `json:"email"`
	DniCuit         pgtype.Text        `json:"dni_cuit"`
	Address         pgtype.Text        `json:"address"`
	Notes           pgtype.Text        `json:"notes"`
	ClientType      string             `json:"client_type"`
	Search          interface{}        `json:"search"`
}

type Device struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	ClientID        int64              `json:"client_id"`
	BrandID         int64              `json:"brand_id"`
	ModelID         pgtype.Int8        `json:"model_id"`
	ArticleTypeID   int64              `json:"article_type_id"`
	SerialNumber    pgtype.Text        `json:"serial_number"`
	Color           pgtype.Text        `json:"color"`
	Description     pgtype.Text        `json:"description"`
}

type DeviceModel struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	BrandID         int64              `json:"brand_id"`
	Name            string             `json:"name"`
}

type Part struct {
	ID               int64              `json:"id"`
	Ucode            pgtype.UUID        `json:"ucode"`
	CreatedTs        pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID  pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs         pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID   pgtype.Int8        `json:"voided_by_user_id"`
	Sku              pgtype.Text        `json:"sku"`
	Name             string             `json:"name"`
	Description      pgtype.Text        `json:"description"`
	Unit             string             `json:"unit"`
	CurrentStock     pgtype.Numeric     `json:"current_stock"`
	ReorderLevel     pgtype.Numeric     `json:"reorder_level"`
	DefaultCost      pgtype.Numeric     `json:"default_cost"`
	DefaultSalePrice pgtype.Numeric     `json:"default_sale_price"`
}

type PartMovement struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	PartID          int64              `json:"part_id"`
	MovementType    string             `json:"movement_type"`
	Quantity        pgtype.Numeric     `json:"quantity"`
	UnitCost        pgtype.Numeric     `json:"unit_cost"`
	SupplierID      pgtype.Int8        `json:"supplier_id"`
	WorkOrderID     pgtype.Int8        `json:"work_order_id"`
	TransactionID   pgtype.Int8        `json:"transaction_id"`
	Notes           pgtype.Text        `json:"notes"`
}

type RecurringExpense struct {
	ID                int64              `json:"id"`
	Ucode             pgtype.UUID        `json:"ucode"`
	CreatedTs         pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID   pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs          pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID    pgtype.Int8        `json:"voided_by_user_id"`
	Name              string             `json:"name"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          string             `json:"currency"`
	DayOfMonth        int32              `json:"day_of_month"`
	Category          string             `json:"category"`
	PaymentMethod     string             `json:"payment_method"`
	SupplierID        pgtype.Int8        `json:"supplier_id"`
	Description       pgtype.Text        `json:"description"`
	Active            bool               `json:"active"`
	LastGeneratedDate pgtype.Date        `json:"last_generated_date"`
}

type Session struct {
	ID         []byte             `json:"id"`
	UserID     int64              `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedTs pgtype.Timestamptz `json:"last_used_ts"`
	Ip         *netip.Addr        `json:"ip"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedTs  pgtype.Timestamptz `json:"created_ts"`
}

type Supplier struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Name            string             `json:"name"`
	Phone           pgtype.Text        `json:"phone"`
	Email           pgtype.Text        `json:"email"`
	Notes           pgtype.Text        `json:"notes"`
}

type Transaction struct {
	ID                 int64              `json:"id"`
	Ucode              pgtype.UUID        `json:"ucode"`
	CreatedTs          pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID    pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs           pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID     pgtype.Int8        `json:"voided_by_user_id"`
	TransactionType    string             `json:"transaction_type"`
	Amount             pgtype.Numeric     `json:"amount"`
	Currency           string             `json:"currency"`
	FxRateToArs        pgtype.Numeric     `json:"fx_rate_to_ars"`
	TransactionDate    pgtype.Date        `json:"transaction_date"`
	PaymentMethod      string             `json:"payment_method"`
	Category           string             `json:"category"`
	CounterpartyType   string             `json:"counterparty_type"`
	ClientID           pgtype.Int8        `json:"client_id"`
	SupplierID         pgtype.Int8        `json:"supplier_id"`
	WorkOrderID        pgtype.Int8        `json:"work_order_id"`
	Description        pgtype.Text        `json:"description"`
	RecurringExpenseID pgtype.Int8        `json:"recurring_expense_id"`
}

type User struct {
	ID              int64              `json:"id"`
	Ucode           pgtype.UUID        `json:"ucode"`
	CreatedTs       pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs        pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID  pgtype.Int8        `json:"voided_by_user_id"`
	Username        string             `json:"username"`
	PasswordHash    string             `json:"password_hash"`
	FullName        string             `json:"full_name"`
	Role            string             `json:"role"`
	LastLoginTs     pgtype.Timestamptz `json:"last_login_ts"`
}

type WoNumberCounter struct {
	Year    int32 `json:"year"`
	LastSeq int64 `json:"last_seq"`
}

type WorkOrder struct {
	ID                 int64              `json:"id"`
	Ucode              pgtype.UUID        `json:"ucode"`
	CreatedTs          pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID    pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs           pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID     pgtype.Int8        `json:"voided_by_user_id"`
	WoNumber           string             `json:"wo_number"`
	DeviceID           int64              `json:"device_id"`
	ClientID           int64              `json:"client_id"`
	ServiceType        string             `json:"service_type"`
	Status             string             `json:"status"`
	ReportedIssue      string             `json:"reported_issue"`
	Diagnosis          pgtype.Text        `json:"diagnosis"`
	QuoteAmount        pgtype.Numeric     `json:"quote_amount"`
	QuoteCurrency      string             `json:"quote_currency"`
	QuoteSentTs        pgtype.Timestamptz `json:"quote_sent_ts"`
	QuoteApprovedTs    pgtype.Timestamptz `json:"quote_approved_ts"`
	QuoteRejectedTs    pgtype.Timestamptz `json:"quote_rejected_ts"`
	FinalAmount        pgtype.Numeric     `json:"final_amount"`
	LaborAmount        pgtype.Numeric     `json:"labor_amount"`
	PartsAmount        pgtype.Numeric     `json:"parts_amount"`
	IntakeNotes        pgtype.Text        `json:"intake_notes"`
	Accessories        pgtype.Text        `json:"accessories"`
	DevicePinEncrypted pgtype.Text        `json:"device_pin_encrypted"`
	ReceivedTs         pgtype.Timestamptz `json:"received_ts"`
	StartedTs          pgtype.Timestamptz `json:"started_ts"`
	ReadyTs            pgtype.Timestamptz `json:"ready_ts"`
	DeliveredTs        pgtype.Timestamptz `json:"delivered_ts"`
	CancelledTs        pgtype.Timestamptz `json:"cancelled_ts"`
	CancelReason       pgtype.Text        `json:"cancel_reason"`
}

type WorkOrderPart struct {
	ID               int64              `json:"id"`
	Ucode            pgtype.UUID        `json:"ucode"`
	CreatedTs        pgtype.Timestamptz `json:"created_ts"`
	CreatedByUserID  pgtype.Int8        `json:"created_by_user_id"`
	VoidedTs         pgtype.Timestamptz `json:"voided_ts"`
	VoidedByUserID   pgtype.Int8        `json:"voided_by_user_id"`
	WorkOrderID      int64              `json:"work_order_id"`
	PartID           int64              `json:"part_id"`
	Quantity         pgtype.Numeric     `json:"quantity"`
	UnitPriceCharged pgtype.Numeric     `json:"unit_price_charged"`
	CostUnit         pgtype.Numeric     `json:"cost_unit"`
	PartMovementID   pgtype.Int8        `json:"part_movement_id"`
}
