// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: parts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPartMovements = `-- name: CountPartMovements :one
SELECT count(*)::bigint
FROM rp.part_movements
WHERE part_id = $1 AND voided_ts IS NULL
`

func (q *Queries) CountPartMovements(ctx context.Context, partID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPartMovements, partID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countParts = `-- name: CountParts :one
SELECT count(*)::bigint
FROM rp.parts
WHERE voided_ts IS NULL
  AND ($1::text = ''
       OR lower(name) LIKE lower('%' || $1::text || '%')
       OR (sku IS NOT NULL AND lower(sku) LIKE lower($1::text || '%')))
  AND (NOT $2::bool
       OR (reorder_level IS NOT NULL AND current_stock < reorder_level))
`

type CountPartsParams struct {
	Q        string `json:"q"`
	LowStock bool   `json:"low_stock"`
}

func (q *Queries) CountParts(ctx context.Context, arg CountPartsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParts, arg.Q, arg.LowStock)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createPart = `-- name: CreatePart :one
INSERT INTO rp.parts (sku, name, description, unit, reorder_level, default_cost, default_sale_price, created_by_user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, sku, name, description, unit, current_stock, reorder_level, default_cost, default_sale_price
`

type CreatePartParams struct {
	Sku              pgtype.Text    `json:"sku"`
	Name             string         `json:"name"`
	Description      pgtype.Text    `json:"description"`
	Unit             string         `json:"unit"`
	ReorderLevel     pgtype.Numeric `json:"reorder_level"`
	DefaultCost      pgtype.Numeric `json:"default_cost"`
	DefaultSalePrice pgtype.Numeric `json:"default_sale_price"`
	CreatedByUserID  pgtype.Int8    `json:"created_by_user_id"`
}

func (q *Queries) CreatePart(ctx context.Context, arg CreatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, createPart,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.ReorderLevel,
		arg.DefaultCost,
		arg.DefaultSalePrice,
		arg.CreatedByUserID,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.CurrentStock,
		&i.ReorderLevel,
		&i.DefaultCost,
		&i.DefaultSalePrice,
	)
	return i, err
}

const createPartMovement = `-- name: CreatePartMovement :one
INSERT INTO rp.part_movements (
  part_id, movement_type, quantity, unit_cost,
  supplier_id, work_order_id, transaction_id, notes, created_by_user_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, part_id, movement_type, quantity, unit_cost, supplier_id, work_order_id, transaction_id, notes
`

type CreatePartMovementParams struct {
	PartID          int64          `json:"part_id"`
	MovementType    string         `json:"movement_type"`
	Quantity        pgtype.Numeric `json:"quantity"`
	UnitCost        pgtype.Numeric `json:"unit_cost"`
	SupplierID      pgtype.Int8    `json:"supplier_id"`
	WorkOrderID     pgtype.Int8    `json:"work_order_id"`
	TransactionID   pgtype.Int8    `json:"transaction_id"`
	Notes           pgtype.Text    `json:"notes"`
	CreatedByUserID pgtype.Int8    `json:"created_by_user_id"`
}

func (q *Queries) CreatePartMovement(ctx context.Context, arg CreatePartMovementParams) (PartMovement, error) {
	row := q.db.QueryRow(ctx, createPartMovement,
		arg.PartID,
		arg.MovementType,
		arg.Quantity,
		arg.UnitCost,
		arg.SupplierID,
		arg.WorkOrderID,
		arg.TransactionID,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i PartMovement
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.PartID,
		&i.MovementType,
		&i.Quantity,
		&i.UnitCost,
		&i.SupplierID,
		&i.WorkOrderID,
		&i.TransactionID,
		&i.Notes,
	)
	return i, err
}

const getPartByID = `-- name: GetPartByID :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, sku, name, description, unit, current_stock, reorder_level, default_cost, default_sale_price FROM rp.parts WHERE id = $1 AND voided_ts IS NULL
`

func (q *Queries) GetPartByID(ctx context.Context, id int64) (Part, error) {
	row := q.db.QueryRow(ctx, getPartByID, id)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.CurrentStock,
		&i.ReorderLevel,
		&i.DefaultCost,
		&i.DefaultSalePrice,
	)
	return i, err
}

const getPartByUcode = `-- name: GetPartByUcode :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, sku, name, description, unit, current_stock, reorder_level, default_cost, default_sale_price FROM rp.parts WHERE ucode = $1 AND voided_ts IS NULL
`

func (q *Queries) GetPartByUcode(ctx context.Context, ucode pgtype.UUID) (Part, error) {
	row := q.db.QueryRow(ctx, getPartByUcode, ucode)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.CurrentStock,
		&i.ReorderLevel,
		&i.DefaultCost,
		&i.DefaultSalePrice,
	)
	return i, err
}

const getPartMovementByUcode = `-- name: GetPartMovementByUcode :one
SELECT
  m.id, m.ucode, m.created_ts, m.created_by_user_id, m.voided_ts, m.voided_by_user_id, m.part_id, m.movement_type, m.quantity, m.unit_cost, m.supplier_id, m.work_order_id, m.transaction_id, m.notes,
  s.ucode AS supplier_ucode, s.name AS supplier_name,
  wo.ucode AS work_order_ucode, wo.wo_number AS work_order_number,
  t.ucode AS transaction_ucode
FROM rp.part_movements m
LEFT JOIN rp.suppliers s ON s.id = m.supplier_id
LEFT JOIN rp.work_orders wo ON wo.id = m.work_order_id
LEFT JOIN rp.transactions t ON t.id = m.transaction_id
WHERE m.ucode = $1
  AND m.voided_ts IS NULL
`

type GetPartMovementByUcodeRow struct {
	PartMovement     PartMovement `json:"part_movement"`
	SupplierUcode    pgtype.UUID  `json:"supplier_ucode"`
	SupplierName     pgtype.Text  `json:"supplier_name"`
	WorkOrderUcode   pgtype.UUID  `json:"work_order_ucode"`
	WorkOrderNumber  pgtype.Text  `json:"work_order_number"`
	TransactionUcode pgtype.UUID  `json:"transaction_ucode"`
}

func (q *Queries) GetPartMovementByUcode(ctx context.Context, ucode pgtype.UUID) (GetPartMovementByUcodeRow, error) {
	row := q.db.QueryRow(ctx, getPartMovementByUcode, ucode)
	var i GetPartMovementByUcodeRow
	err := row.Scan(
		&i.PartMovement.ID,
		&i.PartMovement.Ucode,
		&i.PartMovement.CreatedTs,
		&i.PartMovement.CreatedByUserID,
		&i.PartMovement.VoidedTs,
		&i.PartMovement.VoidedByUserID,
		&i.PartMovement.PartID,
		&i.PartMovement.MovementType,
		&i.PartMovement.Quantity,
		&i.PartMovement.UnitCost,
		&i.PartMovement.SupplierID,
		&i.PartMovement.WorkOrderID,
		&i.PartMovement.TransactionID,
		&i.PartMovement.Notes,
		&i.SupplierUcode,
		&i.SupplierName,
		&i.WorkOrderUcode,
		&i.WorkOrderNumber,
		&i.TransactionUcode,
	)
	return i, err
}

const listPartMovements = `-- name: ListPartMovements :many
SELECT
  m.id, m.ucode, m.created_ts, m.created_by_user_id, m.voided_ts, m.voided_by_user_id, m.part_id, m.movement_type, m.quantity, m.unit_cost, m.supplier_id, m.work_order_id, m.transaction_id, m.notes,
  s.ucode AS supplier_ucode, s.name AS supplier_name,
  wo.ucode AS work_order_ucode, wo.wo_number AS work_order_number,
  t.ucode AS transaction_ucode
FROM rp.part_movements m
LEFT JOIN rp.suppliers s ON s.id = m.supplier_id
LEFT JOIN rp.work_orders wo ON wo.id = m.work_order_id
LEFT JOIN rp.transactions t ON t.id = m.transaction_id
WHERE m.part_id = $1
  AND m.voided_ts IS NULL
ORDER BY m.created_ts DESC, m.id DESC
LIMIT $3::int OFFSET $2::int
`

type ListPartMovementsParams struct {
	PartID     int64 `json:"part_id"`
	PageOffset int32 `json:"page_offset"`
	PageSize   int32 `json:"page_size"`
}

type ListPartMovementsRow struct {
	PartMovement     PartMovement `json:"part_movement"`
	SupplierUcode    pgtype.UUID  `json:"supplier_ucode"`
	SupplierName     pgtype.Text  `json:"supplier_name"`
	WorkOrderUcode   pgtype.UUID  `json:"work_order_ucode"`
	WorkOrderNumber  pgtype.Text  `json:"work_order_number"`
	TransactionUcode pgtype.UUID  `json:"transaction_ucode"`
}

func (q *Queries) ListPartMovements(ctx context.Context, arg ListPartMovementsParams) ([]ListPartMovementsRow, error) {
	rows, err := q.db.Query(ctx, listPartMovements, arg.PartID, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartMovementsRow{}
	for rows.Next() {
		var i ListPartMovementsRow
		if err := rows.Scan(
			&i.PartMovement.ID,
			&i.PartMovement.Ucode,
			&i.PartMovement.CreatedTs,
			&i.PartMovement.CreatedByUserID,
			&i.PartMovement.VoidedTs,
			&i.PartMovement.VoidedByUserID,
			&i.PartMovement.PartID,
			&i.PartMovement.MovementType,
			&i.PartMovement.Quantity,
			&i.PartMovement.UnitCost,
			&i.PartMovement.SupplierID,
			&i.PartMovement.WorkOrderID,
			&i.PartMovement.TransactionID,
			&i.PartMovement.Notes,
			&i.SupplierUcode,
			&i.SupplierName,
			&i.WorkOrderUcode,
			&i.WorkOrderNumber,
			&i.TransactionUcode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchParts = `-- name: SearchParts :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, sku, name, description, unit, current_stock, reorder_level, default_cost, default_sale_price
FROM rp.parts
WHERE voided_ts IS NULL
  AND ($1::text = ''
       OR lower(name) LIKE lower('%' || $1::text || '%')
       OR (sku IS NOT NULL AND lower(sku) LIKE lower($1::text || '%')))
  AND (NOT $2::bool
       OR (reorder_level IS NOT NULL AND current_stock < reorder_level))
ORDER BY name ASC
LIMIT $4::int OFFSET $3::int
`

type SearchPartsParams struct {
	Q          string `json:"q"`
	LowStock   bool   `json:"low_stock"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

func (q *Queries) SearchParts(ctx context.Context, arg SearchPartsParams) ([]Part, error) {
	rows, err := q.db.Query(ctx, searchParts,
		arg.Q,
		arg.LowStock,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Part{}
	for rows.Next() {
		var i Part
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.Sku,
			&i.Name,
			&i.Description,
			&i.Unit,
			&i.CurrentStock,
			&i.ReorderLevel,
			&i.DefaultCost,
			&i.DefaultSalePrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePart = `-- name: SoftDeletePart :exec
UPDATE rp.parts SET voided_ts = now(), voided_by_user_id = $2
WHERE id = $1 AND voided_ts IS NULL
`

type SoftDeletePartParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeletePart(ctx context.Context, arg SoftDeletePartParams) error {
	_, err := q.db.Exec(ctx, softDeletePart, arg.ID, arg.VoidedByUserID)
	return err
}

const softDeletePartMovement = `-- name: SoftDeletePartMovement :exec
UPDATE rp.part_movements SET voided_ts = now(), voided_by_user_id = $2
WHERE id = $1 AND voided_ts IS NULL
`

type SoftDeletePartMovementParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeletePartMovement(ctx context.Context, arg SoftDeletePartMovementParams) error {
	_, err := q.db.Exec(ctx, softDeletePartMovement, arg.ID, arg.VoidedByUserID)
	return err
}

const updatePart = `-- name: UpdatePart :one
UPDATE rp.parts SET
  sku = $2, name = $3, description = $4, unit = $5,
  reorder_level = $6, default_cost = $7, default_sale_price = $8
WHERE id = $1 AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, sku, name, description, unit, current_stock, reorder_level, default_cost, default_sale_price
`

type UpdatePartParams struct {
	ID               int64          `json:"id"`
	Sku              pgtype.Text    `json:"sku"`
	Name             string         `json:"name"`
	Description      pgtype.Text    `json:"description"`
	Unit             string         `json:"unit"`
	ReorderLevel     pgtype.Numeric `json:"reorder_level"`
	DefaultCost      pgtype.Numeric `json:"default_cost"`
	DefaultSalePrice pgtype.Numeric `json:"default_sale_price"`
}

func (q *Queries) UpdatePart(ctx context.Context, arg UpdatePartParams) (Part, error) {
	row := q.db.QueryRow(ctx, updatePart,
		arg.ID,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Unit,
		arg.ReorderLevel,
		arg.DefaultCost,
		arg.DefaultSalePrice,
	)
	var i Part
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Unit,
		&i.CurrentStock,
		&i.ReorderLevel,
		&i.DefaultCost,
		&i.DefaultSalePrice,
	)
	return i, err
}
