// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountClients(ctx context.Context, q_ string) (int64, error)
	CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error)
	CountWorkOrders(ctx context.Context, arg CountWorkOrdersParams) (int64, error)
	CreateArticleType(ctx context.Context, arg CreateArticleTypeParams) (ArticleType, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateDeviceModel(ctx context.Context, arg CreateDeviceModelParams) (DeviceModel, error)
	CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	// Transaction financial identity is immutable after creation: transaction_type,
	// amount, currency, counterparty_type, and relation FKs are not patched. If one
	// of those is wrong, soft-delete the row and create a replacement.
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id []byte) error
	GetArticleTypeByUcode(ctx context.Context, ucode pgtype.UUID) (ArticleType, error)
	GetBrandByUcode(ctx context.Context, ucode pgtype.UUID) (Brand, error)
	GetClientByPhone(ctx context.Context, phone pgtype.Text) (Client, error)
	GetClientByUcode(ctx context.Context, ucode pgtype.UUID) (Client, error)
	GetDeviceByUcode(ctx context.Context, ucode pgtype.UUID) (GetDeviceByUcodeRow, error)
	GetDeviceModelByUcode(ctx context.Context, ucode pgtype.UUID) (GetDeviceModelByUcodeRow, error)
	GetRecurringExpenseByUcode(ctx context.Context, ucode pgtype.UUID) (GetRecurringExpenseByUcodeRow, error)
	GetSessionWithUser(ctx context.Context, id []byte) (GetSessionWithUserRow, error)
	GetSupplierByUcode(ctx context.Context, ucode pgtype.UUID) (Supplier, error)
	GetTransactionByUcode(ctx context.Context, ucode pgtype.UUID) (GetTransactionByUcodeRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetWorkOrderByUcode(ctx context.Context, ucode pgtype.UUID) (GetWorkOrderByUcodeRow, error)
	ListArticleTypes(ctx context.Context) ([]ArticleType, error)
	ListBrands(ctx context.Context) ([]Brand, error)
	ListClientDevices(ctx context.Context, clientID int64) ([]ListClientDevicesRow, error)
	ListDeviceModelsByBrand(ctx context.Context, brandID int64) ([]ListDeviceModelsByBrandRow, error)
	ListDueRecurringExpenses(ctx context.Context, dollar_1 pgtype.Date) ([]RecurringExpense, error)
	ListRecurringExpenses(ctx context.Context) ([]ListRecurringExpensesRow, error)
	ListSuppliers(ctx context.Context) ([]Supplier, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	ListWorkOrderTransactions(ctx context.Context, workOrderID pgtype.Int8) ([]ListWorkOrderTransactionsRow, error)
	ListWorkOrders(ctx context.Context, arg ListWorkOrdersParams) ([]ListWorkOrdersRow, error)
	MarkRecurringExpenseGenerated(ctx context.Context, arg MarkRecurringExpenseGeneratedParams) error
	ReportAgingReadyWorkOrders(ctx context.Context) ([]ReportAgingReadyWorkOrdersRow, error)
	ReportBalance(ctx context.Context, arg ReportBalanceParams) (ReportBalanceRow, error)
	ReportDashboardCounters(ctx context.Context) (ReportDashboardCountersRow, error)
	ReportPnLByCategory(ctx context.Context, arg ReportPnLByCategoryParams) ([]ReportPnLByCategoryRow, error)
	ReportTopClientsByRevenue(ctx context.Context) ([]ReportTopClientsByRevenueRow, error)
	ReportWorkOrderCountsByStatus(ctx context.Context) ([]ReportWorkOrderCountsByStatusRow, error)
	SearchClients(ctx context.Context, arg SearchClientsParams) ([]Client, error)
	SearchDevices(ctx context.Context, arg SearchDevicesParams) ([]SearchDevicesRow, error)
	SetWorkOrderFinals(ctx context.Context, arg SetWorkOrderFinalsParams) (WorkOrder, error)
	SetWorkOrderQuote(ctx context.Context, arg SetWorkOrderQuoteParams) (WorkOrder, error)
	SetWorkOrderQuoteOutcome(ctx context.Context, arg SetWorkOrderQuoteOutcomeParams) (WorkOrder, error)
	SoftDeleteArticleType(ctx context.Context, arg SoftDeleteArticleTypeParams) error
	SoftDeleteBrand(ctx context.Context, arg SoftDeleteBrandParams) error
	SoftDeleteClient(ctx context.Context, arg SoftDeleteClientParams) error
	SoftDeleteDevice(ctx context.Context, arg SoftDeleteDeviceParams) error
	SoftDeleteDeviceModel(ctx context.Context, arg SoftDeleteDeviceModelParams) error
	SoftDeleteRecurringExpense(ctx context.Context, arg SoftDeleteRecurringExpenseParams) error
	SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) error
	SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error
	SoftDeleteWorkOrder(ctx context.Context, arg SoftDeleteWorkOrderParams) error
	TouchSession(ctx context.Context, id []byte) error
	UpdateArticleType(ctx context.Context, arg UpdateArticleTypeParams) (ArticleType, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	UpdateDeviceModel(ctx context.Context, arg UpdateDeviceModelParams) (DeviceModel, error)
	UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateWorkOrderFields(ctx context.Context, arg UpdateWorkOrderFieldsParams) (WorkOrder, error)
	UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error)
}

var _ Querier = (*Queries)(nil)
