// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteSession(ctx context.Context, id []byte) error
	GetSessionWithUser(ctx context.Context, id []byte) (GetSessionWithUserRow, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	TouchSession(ctx context.Context, id []byte) error
	UpdateUserLastLogin(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
