// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recurring_expenses.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO rp.recurring_expenses (
  name,
  amount,
  currency,
  day_of_month,
  category,
  payment_method,
  supplier_id,
  description,
  active,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, amount, currency, day_of_month, category, payment_method, supplier_id, description, active, last_generated_date
`

type CreateRecurringExpenseParams struct {
	Name            string         `json:"name"`
	Amount          pgtype.Numeric `json:"amount"`
	Currency        string         `json:"currency"`
	DayOfMonth      int32          `json:"day_of_month"`
	Category        string         `json:"category"`
	PaymentMethod   string         `json:"payment_method"`
	SupplierID      pgtype.Int8    `json:"supplier_id"`
	Description     pgtype.Text    `json:"description"`
	Active          bool           `json:"active"`
	CreatedByUserID pgtype.Int8    `json:"created_by_user_id"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.DayOfMonth,
		arg.Category,
		arg.PaymentMethod,
		arg.SupplierID,
		arg.Description,
		arg.Active,
		arg.CreatedByUserID,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.DayOfMonth,
		&i.Category,
		&i.PaymentMethod,
		&i.SupplierID,
		&i.Description,
		&i.Active,
		&i.LastGeneratedDate,
	)
	return i, err
}

const getRecurringExpenseByUcode = `-- name: GetRecurringExpenseByUcode :one
SELECT re.id, re.ucode, re.created_ts, re.created_by_user_id, re.voided_ts, re.voided_by_user_id, re.name, re.amount, re.currency, re.day_of_month, re.category, re.payment_method, re.supplier_id, re.description, re.active, re.last_generated_date, s.ucode AS supplier_ucode, s.name AS supplier_name
FROM rp.recurring_expenses re
LEFT JOIN rp.suppliers s ON s.id = re.supplier_id
WHERE re.ucode = $1
  AND re.voided_ts IS NULL
`

type GetRecurringExpenseByUcodeRow struct {
	RecurringExpense RecurringExpense `json:"recurring_expense"`
	SupplierUcode    pgtype.UUID      `json:"supplier_ucode"`
	SupplierName     pgtype.Text      `json:"supplier_name"`
}

func (q *Queries) GetRecurringExpenseByUcode(ctx context.Context, ucode pgtype.UUID) (GetRecurringExpenseByUcodeRow, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseByUcode, ucode)
	var i GetRecurringExpenseByUcodeRow
	err := row.Scan(
		&i.RecurringExpense.ID,
		&i.RecurringExpense.Ucode,
		&i.RecurringExpense.CreatedTs,
		&i.RecurringExpense.CreatedByUserID,
		&i.RecurringExpense.VoidedTs,
		&i.RecurringExpense.VoidedByUserID,
		&i.RecurringExpense.Name,
		&i.RecurringExpense.Amount,
		&i.RecurringExpense.Currency,
		&i.RecurringExpense.DayOfMonth,
		&i.RecurringExpense.Category,
		&i.RecurringExpense.PaymentMethod,
		&i.RecurringExpense.SupplierID,
		&i.RecurringExpense.Description,
		&i.RecurringExpense.Active,
		&i.RecurringExpense.LastGeneratedDate,
		&i.SupplierUcode,
		&i.SupplierName,
	)
	return i, err
}

const listDueRecurringExpenses = `-- name: ListDueRecurringExpenses :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, amount, currency, day_of_month, category, payment_method, supplier_id, description, active, last_generated_date
FROM rp.recurring_expenses
WHERE voided_ts IS NULL
  AND active = true
  AND (last_generated_date IS NULL OR last_generated_date < $1::date)
ORDER BY day_of_month ASC, name ASC
`

func (q *Queries) ListDueRecurringExpenses(ctx context.Context, dollar_1 pgtype.Date) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listDueRecurringExpenses, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecurringExpense{}
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.Name,
			&i.Amount,
			&i.Currency,
			&i.DayOfMonth,
			&i.Category,
			&i.PaymentMethod,
			&i.SupplierID,
			&i.Description,
			&i.Active,
			&i.LastGeneratedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpenses = `-- name: ListRecurringExpenses :many
SELECT re.id, re.ucode, re.created_ts, re.created_by_user_id, re.voided_ts, re.voided_by_user_id, re.name, re.amount, re.currency, re.day_of_month, re.category, re.payment_method, re.supplier_id, re.description, re.active, re.last_generated_date, s.ucode AS supplier_ucode, s.name AS supplier_name
FROM rp.recurring_expenses re
LEFT JOIN rp.suppliers s ON s.id = re.supplier_id
WHERE re.voided_ts IS NULL
ORDER BY re.active DESC, re.day_of_month ASC, re.name ASC
`

type ListRecurringExpensesRow struct {
	RecurringExpense RecurringExpense `json:"recurring_expense"`
	SupplierUcode    pgtype.UUID      `json:"supplier_ucode"`
	SupplierName     pgtype.Text      `json:"supplier_name"`
}

func (q *Queries) ListRecurringExpenses(ctx context.Context) ([]ListRecurringExpensesRow, error) {
	rows, err := q.db.Query(ctx, listRecurringExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecurringExpensesRow{}
	for rows.Next() {
		var i ListRecurringExpensesRow
		if err := rows.Scan(
			&i.RecurringExpense.ID,
			&i.RecurringExpense.Ucode,
			&i.RecurringExpense.CreatedTs,
			&i.RecurringExpense.CreatedByUserID,
			&i.RecurringExpense.VoidedTs,
			&i.RecurringExpense.VoidedByUserID,
			&i.RecurringExpense.Name,
			&i.RecurringExpense.Amount,
			&i.RecurringExpense.Currency,
			&i.RecurringExpense.DayOfMonth,
			&i.RecurringExpense.Category,
			&i.RecurringExpense.PaymentMethod,
			&i.RecurringExpense.SupplierID,
			&i.RecurringExpense.Description,
			&i.RecurringExpense.Active,
			&i.RecurringExpense.LastGeneratedDate,
			&i.SupplierUcode,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecurringExpenseGenerated = `-- name: MarkRecurringExpenseGenerated :exec
UPDATE rp.recurring_expenses
SET last_generated_date = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type MarkRecurringExpenseGeneratedParams struct {
	ID                int64       `json:"id"`
	LastGeneratedDate pgtype.Date `json:"last_generated_date"`
}

func (q *Queries) MarkRecurringExpenseGenerated(ctx context.Context, arg MarkRecurringExpenseGeneratedParams) error {
	_, err := q.db.Exec(ctx, markRecurringExpenseGenerated, arg.ID, arg.LastGeneratedDate)
	return err
}

const softDeleteRecurringExpense = `-- name: SoftDeleteRecurringExpense :exec
UPDATE rp.recurring_expenses
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type SoftDeleteRecurringExpenseParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteRecurringExpense(ctx context.Context, arg SoftDeleteRecurringExpenseParams) error {
	_, err := q.db.Exec(ctx, softDeleteRecurringExpense, arg.ID, arg.VoidedByUserID)
	return err
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE rp.recurring_expenses
SET
  name = $2,
  amount = $3,
  currency = $4,
  day_of_month = $5,
  category = $6,
  payment_method = $7,
  supplier_id = $8,
  description = $9,
  active = $10
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, amount, currency, day_of_month, category, payment_method, supplier_id, description, active, last_generated_date
`

type UpdateRecurringExpenseParams struct {
	ID            int64          `json:"id"`
	Name          string         `json:"name"`
	Amount        pgtype.Numeric `json:"amount"`
	Currency      string         `json:"currency"`
	DayOfMonth    int32          `json:"day_of_month"`
	Category      string         `json:"category"`
	PaymentMethod string         `json:"payment_method"`
	SupplierID    pgtype.Int8    `json:"supplier_id"`
	Description   pgtype.Text    `json:"description"`
	Active        bool           `json:"active"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Currency,
		arg.DayOfMonth,
		arg.Category,
		arg.PaymentMethod,
		arg.SupplierID,
		arg.Description,
		arg.Active,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Amount,
		&i.Currency,
		&i.DayOfMonth,
		&i.Category,
		&i.PaymentMethod,
		&i.SupplierID,
		&i.Description,
		&i.Active,
		&i.LastGeneratedDate,
	)
	return i, err
}
