// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reports.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reportAgingReadyWorkOrders = `-- name: ReportAgingReadyWorkOrders :many
SELECT wo.ucode, wo.wo_number, wo.ready_ts, c.name AS client_name
FROM rp.work_orders wo
JOIN rp.clients c ON c.id = wo.client_id
WHERE wo.voided_ts IS NULL
  AND wo.status = 'ready'
  AND wo.ready_ts < now() - INTERVAL '7 days'
ORDER BY wo.ready_ts ASC
`

type ReportAgingReadyWorkOrdersRow struct {
	Ucode      pgtype.UUID        `json:"ucode"`
	WoNumber   string             `json:"wo_number"`
	ReadyTs    pgtype.Timestamptz `json:"ready_ts"`
	ClientName string             `json:"client_name"`
}

func (q *Queries) ReportAgingReadyWorkOrders(ctx context.Context) ([]ReportAgingReadyWorkOrdersRow, error) {
	rows, err := q.db.Query(ctx, reportAgingReadyWorkOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportAgingReadyWorkOrdersRow{}
	for rows.Next() {
		var i ReportAgingReadyWorkOrdersRow
		if err := rows.Scan(
			&i.Ucode,
			&i.WoNumber,
			&i.ReadyTs,
			&i.ClientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportBalance = `-- name: ReportBalance :one
SELECT
  COALESCE(SUM(CASE WHEN transaction_type = 'income' THEN amount * fx_rate_to_ars ELSE 0 END), 0)::numeric(18, 2) AS income_ars,
  COALESCE(SUM(CASE WHEN transaction_type = 'expense' THEN amount * fx_rate_to_ars ELSE 0 END), 0)::numeric(18, 2) AS expense_ars,
  COUNT(*)::bigint AS transaction_count
FROM rp.transactions
WHERE voided_ts IS NULL
  AND transaction_date BETWEEN $1::date AND $2::date
`

type ReportBalanceParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type ReportBalanceRow struct {
	IncomeArs        pgtype.Numeric `json:"income_ars"`
	ExpenseArs       pgtype.Numeric `json:"expense_ars"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) ReportBalance(ctx context.Context, arg ReportBalanceParams) (ReportBalanceRow, error) {
	row := q.db.QueryRow(ctx, reportBalance, arg.DateFrom, arg.DateTo)
	var i ReportBalanceRow
	err := row.Scan(&i.IncomeArs, &i.ExpenseArs, &i.TransactionCount)
	return i, err
}

const reportDashboardCounters = `-- name: ReportDashboardCounters :one
SELECT
  COALESCE(SUM(CASE WHEN t.transaction_date = (now() AT TIME ZONE 'UTC')::date AND t.transaction_type = 'income' THEN t.amount * t.fx_rate_to_ars ELSE 0 END), 0)::numeric(18, 2) AS income_today_ars,
  COALESCE(SUM(CASE WHEN t.transaction_date = (now() AT TIME ZONE 'UTC')::date AND t.transaction_type = 'expense' THEN t.amount * t.fx_rate_to_ars ELSE 0 END), 0)::numeric(18, 2) AS expense_today_ars,
  COALESCE(SUM(CASE WHEN date_trunc('month', t.transaction_date)::date = date_trunc('month', now() AT TIME ZONE 'UTC')::date AND t.transaction_type = 'income' THEN t.amount * t.fx_rate_to_ars ELSE 0 END), 0)::numeric(18, 2) AS income_month_ars,
  COALESCE(SUM(CASE WHEN date_trunc('month', t.transaction_date)::date = date_trunc('month', now() AT TIME ZONE 'UTC')::date AND t.transaction_type = 'expense' THEN t.amount * t.fx_rate_to_ars ELSE 0 END), 0)::numeric(18, 2) AS expense_month_ars
FROM rp.transactions t
WHERE t.voided_ts IS NULL
`

type ReportDashboardCountersRow struct {
	IncomeTodayArs  pgtype.Numeric `json:"income_today_ars"`
	ExpenseTodayArs pgtype.Numeric `json:"expense_today_ars"`
	IncomeMonthArs  pgtype.Numeric `json:"income_month_ars"`
	ExpenseMonthArs pgtype.Numeric `json:"expense_month_ars"`
}

func (q *Queries) ReportDashboardCounters(ctx context.Context) (ReportDashboardCountersRow, error) {
	row := q.db.QueryRow(ctx, reportDashboardCounters)
	var i ReportDashboardCountersRow
	err := row.Scan(
		&i.IncomeTodayArs,
		&i.ExpenseTodayArs,
		&i.IncomeMonthArs,
		&i.ExpenseMonthArs,
	)
	return i, err
}

const reportLowStockParts = `-- name: ReportLowStockParts :many
SELECT p.ucode, p.name, p.sku, p.unit,
       p.current_stock,
       p.reorder_level,
       (p.reorder_level - p.current_stock)::numeric(10,2) AS deficit
FROM rp.parts p
WHERE p.voided_ts IS NULL
  AND p.reorder_level IS NOT NULL
  AND p.current_stock < p.reorder_level
ORDER BY deficit DESC, p.name ASC
LIMIT $1::int
`

type ReportLowStockPartsRow struct {
	Ucode        pgtype.UUID    `json:"ucode"`
	Name         string         `json:"name"`
	Sku          pgtype.Text    `json:"sku"`
	Unit         string         `json:"unit"`
	CurrentStock pgtype.Numeric `json:"current_stock"`
	ReorderLevel pgtype.Numeric `json:"reorder_level"`
	Deficit      pgtype.Numeric `json:"deficit"`
}

func (q *Queries) ReportLowStockParts(ctx context.Context, maxRows int32) ([]ReportLowStockPartsRow, error) {
	rows, err := q.db.Query(ctx, reportLowStockParts, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportLowStockPartsRow{}
	for rows.Next() {
		var i ReportLowStockPartsRow
		if err := rows.Scan(
			&i.Ucode,
			&i.Name,
			&i.Sku,
			&i.Unit,
			&i.CurrentStock,
			&i.ReorderLevel,
			&i.Deficit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportPnLByCategory = `-- name: ReportPnLByCategory :many
SELECT
  transaction_type,
  category,
  COALESCE(SUM(amount * fx_rate_to_ars), 0)::numeric(18, 2) AS total_ars,
  COUNT(*)::bigint AS transaction_count
FROM rp.transactions
WHERE voided_ts IS NULL
  AND transaction_date BETWEEN $1::date AND $2::date
GROUP BY transaction_type, category
ORDER BY transaction_type, total_ars DESC
`

type ReportPnLByCategoryParams struct {
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
}

type ReportPnLByCategoryRow struct {
	TransactionType  string         `json:"transaction_type"`
	Category         string         `json:"category"`
	TotalArs         pgtype.Numeric `json:"total_ars"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) ReportPnLByCategory(ctx context.Context, arg ReportPnLByCategoryParams) ([]ReportPnLByCategoryRow, error) {
	rows, err := q.db.Query(ctx, reportPnLByCategory, arg.DateFrom, arg.DateTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportPnLByCategoryRow{}
	for rows.Next() {
		var i ReportPnLByCategoryRow
		if err := rows.Scan(
			&i.TransactionType,
			&i.Category,
			&i.TotalArs,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportTopClientsByRevenue = `-- name: ReportTopClientsByRevenue :many
SELECT c.ucode, c.name, COALESCE(SUM(t.amount * t.fx_rate_to_ars), 0)::numeric(18, 2) AS total_ars
FROM rp.transactions t
JOIN rp.clients c ON c.id = t.client_id
WHERE t.voided_ts IS NULL
  AND t.transaction_type = 'income'
  AND t.transaction_date >= ((now() AT TIME ZONE 'UTC')::date - INTERVAL '90 days')
GROUP BY c.ucode, c.name
ORDER BY total_ars DESC
LIMIT 5
`

type ReportTopClientsByRevenueRow struct {
	Ucode    pgtype.UUID    `json:"ucode"`
	Name     string         `json:"name"`
	TotalArs pgtype.Numeric `json:"total_ars"`
}

func (q *Queries) ReportTopClientsByRevenue(ctx context.Context) ([]ReportTopClientsByRevenueRow, error) {
	rows, err := q.db.Query(ctx, reportTopClientsByRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportTopClientsByRevenueRow{}
	for rows.Next() {
		var i ReportTopClientsByRevenueRow
		if err := rows.Scan(&i.Ucode, &i.Name, &i.TotalArs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportWorkOrderCountsByStatus = `-- name: ReportWorkOrderCountsByStatus :many
SELECT status, COUNT(*)::bigint AS count
FROM rp.work_orders
WHERE voided_ts IS NULL
GROUP BY status
`

type ReportWorkOrderCountsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) ReportWorkOrderCountsByStatus(ctx context.Context) ([]ReportWorkOrderCountsByStatusRow, error) {
	rows, err := q.db.Query(ctx, reportWorkOrderCountsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportWorkOrderCountsByStatusRow{}
	for rows.Next() {
		var i ReportWorkOrderCountsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
