// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO rp.sessions (id, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	ID        []byte             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Ip        *netip.Addr        `json:"ip"`
	UserAgent pgtype.Text        `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM rp.sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM rp.sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT s.id, s.user_id, s.expires_at, s.last_used_ts, s.ip, s.user_agent, s.created_ts, u.id, u.ucode, u.created_ts, u.created_by_user_id, u.voided_ts, u.voided_by_user_id, u.username, u.password_hash, u.full_name, u.role, u.last_login_ts
FROM rp.sessions s
JOIN rp.users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.expires_at > now()
  AND u.voided_ts IS NULL
`

type GetSessionWithUserRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id []byte) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.ExpiresAt,
		&i.Session.LastUsedTs,
		&i.Session.Ip,
		&i.Session.UserAgent,
		&i.Session.CreatedTs,
		&i.User.ID,
		&i.User.Ucode,
		&i.User.CreatedTs,
		&i.User.CreatedByUserID,
		&i.User.VoidedTs,
		&i.User.VoidedByUserID,
		&i.User.Username,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Role,
		&i.User.LastLoginTs,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE rp.sessions
SET last_used_ts = now()
WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
