// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: suppliers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO rp.suppliers (
  name,
  phone,
  email,
  notes,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, notes
`

type CreateSupplierParams struct {
	Name            string      `json:"name"`
	Phone           pgtype.Text `json:"phone"`
	Email           pgtype.Text `json:"email"`
	Notes           pgtype.Text `json:"notes"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
		arg.CreatedByUserID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const getSupplierByName = `-- name: GetSupplierByName :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, notes
FROM rp.suppliers
WHERE lower(name) = lower($1)
  AND voided_ts IS NULL
`

func (q *Queries) GetSupplierByName(ctx context.Context, lower string) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByName, lower)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const getSupplierByUcode = `-- name: GetSupplierByUcode :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, notes
FROM rp.suppliers
WHERE ucode = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetSupplierByUcode(ctx context.Context, ucode pgtype.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByUcode, ucode)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, notes
FROM rp.suppliers
WHERE voided_ts IS NULL
ORDER BY name ASC
`

func (q *Queries) ListSuppliers(ctx context.Context) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Ucode,
			&i.CreatedTs,
			&i.CreatedByUserID,
			&i.VoidedTs,
			&i.VoidedByUserID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSupplier = `-- name: SoftDeleteSupplier :exec
UPDATE rp.suppliers
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type SoftDeleteSupplierParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteSupplier(ctx context.Context, arg SoftDeleteSupplierParams) error {
	_, err := q.db.Exec(ctx, softDeleteSupplier, arg.ID, arg.VoidedByUserID)
	return err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE rp.suppliers
SET
  name = $2,
  phone = $3,
  email = $4,
  notes = $5
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, name, phone, email, notes
`

type UpdateSupplierParams struct {
	ID    int64       `json:"id"`
	Name  string      `json:"name"`
	Phone pgtype.Text `json:"phone"`
	Email pgtype.Text `json:"email"`
	Notes pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Notes,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Notes,
	)
	return i, err
}
