// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTransactions = `-- name: CountTransactions :one
SELECT count(*)::bigint
FROM rp.transactions t
WHERE t.voided_ts IS NULL
  AND (NOT $1::bool OR t.transaction_date >= $2::date)
  AND (NOT $3::bool OR t.transaction_date <= $4::date)
  AND ($5::text = '' OR t.transaction_type = $5::text)
  AND ($6::text = '' OR t.category = $6::text)
  AND (NOT $7::bool OR t.work_order_id = $8::bigint)
`

type CountTransactionsParams struct {
	HasFrom         bool        `json:"has_from"`
	DateFrom        pgtype.Date `json:"date_from"`
	HasTo           bool        `json:"has_to"`
	DateTo          pgtype.Date `json:"date_to"`
	TransactionType string      `json:"transaction_type"`
	Category        string      `json:"category"`
	HasWorkOrder    bool        `json:"has_work_order"`
	WorkOrderID     int64       `json:"work_order_id"`
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions,
		arg.HasFrom,
		arg.DateFrom,
		arg.HasTo,
		arg.DateTo,
		arg.TransactionType,
		arg.Category,
		arg.HasWorkOrder,
		arg.WorkOrderID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO rp.transactions (
  transaction_type,
  amount,
  currency,
  fx_rate_to_ars,
  transaction_date,
  payment_method,
  category,
  counterparty_type,
  client_id,
  supplier_id,
  work_order_id,
  description,
  recurring_expense_id,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, transaction_type, amount, currency, fx_rate_to_ars, transaction_date, payment_method, category, counterparty_type, client_id, supplier_id, work_order_id, description, recurring_expense_id
`

type CreateTransactionParams struct {
	TransactionType    string         `json:"transaction_type"`
	Amount             pgtype.Numeric `json:"amount"`
	Currency           string         `json:"currency"`
	FxRateToArs        pgtype.Numeric `json:"fx_rate_to_ars"`
	TransactionDate    pgtype.Date    `json:"transaction_date"`
	PaymentMethod      string         `json:"payment_method"`
	Category           string         `json:"category"`
	CounterpartyType   string         `json:"counterparty_type"`
	ClientID           pgtype.Int8    `json:"client_id"`
	SupplierID         pgtype.Int8    `json:"supplier_id"`
	WorkOrderID        pgtype.Int8    `json:"work_order_id"`
	Description        pgtype.Text    `json:"description"`
	RecurringExpenseID pgtype.Int8    `json:"recurring_expense_id"`
	CreatedByUserID    pgtype.Int8    `json:"created_by_user_id"`
}

// Transaction financial identity is immutable after creation: transaction_type,
// amount, currency, counterparty_type, and relation FKs are not patched. If one
// of those is wrong, soft-delete the row and create a replacement.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.TransactionType,
		arg.Amount,
		arg.Currency,
		arg.FxRateToArs,
		arg.TransactionDate,
		arg.PaymentMethod,
		arg.Category,
		arg.CounterpartyType,
		arg.ClientID,
		arg.SupplierID,
		arg.WorkOrderID,
		arg.Description,
		arg.RecurringExpenseID,
		arg.CreatedByUserID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.FxRateToArs,
		&i.TransactionDate,
		&i.PaymentMethod,
		&i.Category,
		&i.CounterpartyType,
		&i.ClientID,
		&i.SupplierID,
		&i.WorkOrderID,
		&i.Description,
		&i.RecurringExpenseID,
	)
	return i, err
}

const getTransactionByUcode = `-- name: GetTransactionByUcode :one
SELECT
  t.id, t.ucode, t.created_ts, t.created_by_user_id, t.voided_ts, t.voided_by_user_id, t.transaction_type, t.amount, t.currency, t.fx_rate_to_ars, t.transaction_date, t.payment_method, t.category, t.counterparty_type, t.client_id, t.supplier_id, t.work_order_id, t.description, t.recurring_expense_id,
  c.ucode  AS client_ucode, c.name AS client_name,
  s.ucode  AS supplier_ucode, s.name AS supplier_name,
  wo.ucode AS work_order_ucode, wo.wo_number AS work_order_number,
  re.ucode AS recurring_expense_ucode, re.name AS recurring_expense_name
FROM rp.transactions t
LEFT JOIN rp.clients c ON c.id = t.client_id
LEFT JOIN rp.suppliers s ON s.id = t.supplier_id
LEFT JOIN rp.work_orders wo ON wo.id = t.work_order_id
LEFT JOIN rp.recurring_expenses re ON re.id = t.recurring_expense_id
WHERE t.ucode = $1
  AND t.voided_ts IS NULL
`

type GetTransactionByUcodeRow struct {
	Transaction           Transaction `json:"transaction"`
	ClientUcode           pgtype.UUID `json:"client_ucode"`
	ClientName            pgtype.Text `json:"client_name"`
	SupplierUcode         pgtype.UUID `json:"supplier_ucode"`
	SupplierName          pgtype.Text `json:"supplier_name"`
	WorkOrderUcode        pgtype.UUID `json:"work_order_ucode"`
	WorkOrderNumber       pgtype.Text `json:"work_order_number"`
	RecurringExpenseUcode pgtype.UUID `json:"recurring_expense_ucode"`
	RecurringExpenseName  pgtype.Text `json:"recurring_expense_name"`
}

func (q *Queries) GetTransactionByUcode(ctx context.Context, ucode pgtype.UUID) (GetTransactionByUcodeRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByUcode, ucode)
	var i GetTransactionByUcodeRow
	err := row.Scan(
		&i.Transaction.ID,
		&i.Transaction.Ucode,
		&i.Transaction.CreatedTs,
		&i.Transaction.CreatedByUserID,
		&i.Transaction.VoidedTs,
		&i.Transaction.VoidedByUserID,
		&i.Transaction.TransactionType,
		&i.Transaction.Amount,
		&i.Transaction.Currency,
		&i.Transaction.FxRateToArs,
		&i.Transaction.TransactionDate,
		&i.Transaction.PaymentMethod,
		&i.Transaction.Category,
		&i.Transaction.CounterpartyType,
		&i.Transaction.ClientID,
		&i.Transaction.SupplierID,
		&i.Transaction.WorkOrderID,
		&i.Transaction.Description,
		&i.Transaction.RecurringExpenseID,
		&i.ClientUcode,
		&i.ClientName,
		&i.SupplierUcode,
		&i.SupplierName,
		&i.WorkOrderUcode,
		&i.WorkOrderNumber,
		&i.RecurringExpenseUcode,
		&i.RecurringExpenseName,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT
  t.id, t.ucode, t.created_ts, t.created_by_user_id, t.voided_ts, t.voided_by_user_id, t.transaction_type, t.amount, t.currency, t.fx_rate_to_ars, t.transaction_date, t.payment_method, t.category, t.counterparty_type, t.client_id, t.supplier_id, t.work_order_id, t.description, t.recurring_expense_id,
  c.ucode AS client_ucode, c.name AS client_name,
  s.ucode AS supplier_ucode, s.name AS supplier_name,
  wo.ucode AS work_order_ucode, wo.wo_number AS work_order_number,
  re.ucode AS recurring_expense_ucode, re.name AS recurring_expense_name
FROM rp.transactions t
LEFT JOIN rp.clients c ON c.id = t.client_id
LEFT JOIN rp.suppliers s ON s.id = t.supplier_id
LEFT JOIN rp.work_orders wo ON wo.id = t.work_order_id
LEFT JOIN rp.recurring_expenses re ON re.id = t.recurring_expense_id
WHERE t.voided_ts IS NULL
  AND (NOT $1::bool OR t.transaction_date >= $2::date)
  AND (NOT $3::bool OR t.transaction_date <= $4::date)
  AND ($5::text = '' OR t.transaction_type = $5::text)
  AND ($6::text = '' OR t.category = $6::text)
  AND (NOT $7::bool OR t.work_order_id = $8::bigint)
ORDER BY t.transaction_date DESC, t.id DESC
LIMIT $10::int OFFSET $9::int
`

type ListTransactionsParams struct {
	HasFrom         bool        `json:"has_from"`
	DateFrom        pgtype.Date `json:"date_from"`
	HasTo           bool        `json:"has_to"`
	DateTo          pgtype.Date `json:"date_to"`
	TransactionType string      `json:"transaction_type"`
	Category        string      `json:"category"`
	HasWorkOrder    bool        `json:"has_work_order"`
	WorkOrderID     int64       `json:"work_order_id"`
	PageOffset      int32       `json:"page_offset"`
	PageSize        int32       `json:"page_size"`
}

type ListTransactionsRow struct {
	Transaction           Transaction `json:"transaction"`
	ClientUcode           pgtype.UUID `json:"client_ucode"`
	ClientName            pgtype.Text `json:"client_name"`
	SupplierUcode         pgtype.UUID `json:"supplier_ucode"`
	SupplierName          pgtype.Text `json:"supplier_name"`
	WorkOrderUcode        pgtype.UUID `json:"work_order_ucode"`
	WorkOrderNumber       pgtype.Text `json:"work_order_number"`
	RecurringExpenseUcode pgtype.UUID `json:"recurring_expense_ucode"`
	RecurringExpenseName  pgtype.Text `json:"recurring_expense_name"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.HasFrom,
		arg.DateFrom,
		arg.HasTo,
		arg.DateTo,
		arg.TransactionType,
		arg.Category,
		arg.HasWorkOrder,
		arg.WorkOrderID,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.Ucode,
			&i.Transaction.CreatedTs,
			&i.Transaction.CreatedByUserID,
			&i.Transaction.VoidedTs,
			&i.Transaction.VoidedByUserID,
			&i.Transaction.TransactionType,
			&i.Transaction.Amount,
			&i.Transaction.Currency,
			&i.Transaction.FxRateToArs,
			&i.Transaction.TransactionDate,
			&i.Transaction.PaymentMethod,
			&i.Transaction.Category,
			&i.Transaction.CounterpartyType,
			&i.Transaction.ClientID,
			&i.Transaction.SupplierID,
			&i.Transaction.WorkOrderID,
			&i.Transaction.Description,
			&i.Transaction.RecurringExpenseID,
			&i.ClientUcode,
			&i.ClientName,
			&i.SupplierUcode,
			&i.SupplierName,
			&i.WorkOrderUcode,
			&i.WorkOrderNumber,
			&i.RecurringExpenseUcode,
			&i.RecurringExpenseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkOrderTransactions = `-- name: ListWorkOrderTransactions :many
SELECT
  t.id, t.ucode, t.created_ts, t.created_by_user_id, t.voided_ts, t.voided_by_user_id, t.transaction_type, t.amount, t.currency, t.fx_rate_to_ars, t.transaction_date, t.payment_method, t.category, t.counterparty_type, t.client_id, t.supplier_id, t.work_order_id, t.description, t.recurring_expense_id,
  c.ucode AS client_ucode, c.name AS client_name,
  s.ucode AS supplier_ucode, s.name AS supplier_name,
  wo.ucode AS work_order_ucode, wo.wo_number AS work_order_number,
  re.ucode AS recurring_expense_ucode, re.name AS recurring_expense_name
FROM rp.transactions t
LEFT JOIN rp.clients c ON c.id = t.client_id
LEFT JOIN rp.suppliers s ON s.id = t.supplier_id
LEFT JOIN rp.work_orders wo ON wo.id = t.work_order_id
LEFT JOIN rp.recurring_expenses re ON re.id = t.recurring_expense_id
WHERE t.work_order_id = $1
  AND t.voided_ts IS NULL
ORDER BY t.transaction_date DESC, t.id DESC
`

type ListWorkOrderTransactionsRow struct {
	Transaction           Transaction `json:"transaction"`
	ClientUcode           pgtype.UUID `json:"client_ucode"`
	ClientName            pgtype.Text `json:"client_name"`
	SupplierUcode         pgtype.UUID `json:"supplier_ucode"`
	SupplierName          pgtype.Text `json:"supplier_name"`
	WorkOrderUcode        pgtype.UUID `json:"work_order_ucode"`
	WorkOrderNumber       pgtype.Text `json:"work_order_number"`
	RecurringExpenseUcode pgtype.UUID `json:"recurring_expense_ucode"`
	RecurringExpenseName  pgtype.Text `json:"recurring_expense_name"`
}

func (q *Queries) ListWorkOrderTransactions(ctx context.Context, workOrderID pgtype.Int8) ([]ListWorkOrderTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrderTransactions, workOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrderTransactionsRow{}
	for rows.Next() {
		var i ListWorkOrderTransactionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.Ucode,
			&i.Transaction.CreatedTs,
			&i.Transaction.CreatedByUserID,
			&i.Transaction.VoidedTs,
			&i.Transaction.VoidedByUserID,
			&i.Transaction.TransactionType,
			&i.Transaction.Amount,
			&i.Transaction.Currency,
			&i.Transaction.FxRateToArs,
			&i.Transaction.TransactionDate,
			&i.Transaction.PaymentMethod,
			&i.Transaction.Category,
			&i.Transaction.CounterpartyType,
			&i.Transaction.ClientID,
			&i.Transaction.SupplierID,
			&i.Transaction.WorkOrderID,
			&i.Transaction.Description,
			&i.Transaction.RecurringExpenseID,
			&i.ClientUcode,
			&i.ClientName,
			&i.SupplierUcode,
			&i.SupplierName,
			&i.WorkOrderUcode,
			&i.WorkOrderNumber,
			&i.RecurringExpenseUcode,
			&i.RecurringExpenseName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE rp.transactions
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type SoftDeleteTransactionParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.VoidedByUserID)
	return err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE rp.transactions
SET
  transaction_date = $2,
  payment_method = $3,
  category = $4,
  description = $5
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, transaction_type, amount, currency, fx_rate_to_ars, transaction_date, payment_method, category, counterparty_type, client_id, supplier_id, work_order_id, description, recurring_expense_id
`

type UpdateTransactionParams struct {
	ID              int64       `json:"id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	PaymentMethod   string      `json:"payment_method"`
	Category        string      `json:"category"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.TransactionDate,
		arg.PaymentMethod,
		arg.Category,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.FxRateToArs,
		&i.TransactionDate,
		&i.PaymentMethod,
		&i.Category,
		&i.CounterpartyType,
		&i.ClientID,
		&i.SupplierID,
		&i.WorkOrderID,
		&i.Description,
		&i.RecurringExpenseID,
	)
	return i, err
}
