// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO rp.users (username, password_hash, full_name, role, created_by_user_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, username, password_hash, full_name, role, last_login_ts
`

type CreateUserParams struct {
	Username        string      `json:"username"`
	PasswordHash    string      `json:"password_hash"`
	FullName        string      `json:"full_name"`
	Role            string      `json:"role"`
	CreatedByUserID pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.CreatedByUserID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.LastLoginTs,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, username, password_hash, full_name, role, last_login_ts
FROM rp.users
WHERE id = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.LastLoginTs,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, username, password_hash, full_name, role, last_login_ts
FROM rp.users
WHERE username = $1
  AND voided_ts IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.LastLoginTs,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE rp.users
SET last_login_ts = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
