// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: work_orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkOrders = `-- name: CountWorkOrders :one
SELECT count(*)::bigint
FROM rp.work_orders wo
JOIN rp.clients c ON c.id = wo.client_id
JOIN rp.devices d ON d.id = wo.device_id
JOIN rp.brands b ON b.id = d.brand_id
LEFT JOIN rp.device_models dm ON dm.id = d.model_id
JOIN rp.article_types at ON at.id = d.article_type_id
WHERE wo.voided_ts IS NULL
  AND ($1::text = '' OR wo.status = $1::text)
  AND (NOT $2::bool OR wo.client_id = $3::bigint)
  AND (
    $4::text = ''
    OR wo.wo_number ILIKE '%' || $4::text || '%'
    OR c.name ILIKE '%' || $4::text || '%'
    OR c.phone = $4::text
    OR d.serial_number ILIKE $4::text || '%'
  )
`

type CountWorkOrdersParams struct {
	Status    string `json:"status"`
	HasClient bool   `json:"has_client"`
	ClientID  int64  `json:"client_id"`
	Q         string `json:"q"`
}

func (q *Queries) CountWorkOrders(ctx context.Context, arg CountWorkOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkOrders,
		arg.Status,
		arg.HasClient,
		arg.ClientID,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createWorkOrder = `-- name: CreateWorkOrder :one
INSERT INTO rp.work_orders (
  client_id,
  device_id,
  service_type,
  reported_issue,
  intake_notes,
  accessories,
  device_pin_encrypted,
  created_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, wo_number, device_id, client_id, service_type, status, reported_issue, diagnosis, quote_amount, quote_currency, quote_sent_ts, quote_approved_ts, quote_rejected_ts, final_amount, labor_amount, parts_amount, intake_notes, accessories, device_pin_encrypted, received_ts, started_ts, ready_ts, delivered_ts, cancelled_ts, cancel_reason
`

type CreateWorkOrderParams struct {
	ClientID           int64       `json:"client_id"`
	DeviceID           int64       `json:"device_id"`
	ServiceType        string      `json:"service_type"`
	ReportedIssue      string      `json:"reported_issue"`
	IntakeNotes        pgtype.Text `json:"intake_notes"`
	Accessories        pgtype.Text `json:"accessories"`
	DevicePinEncrypted pgtype.Text `json:"device_pin_encrypted"`
	CreatedByUserID    pgtype.Int8 `json:"created_by_user_id"`
}

func (q *Queries) CreateWorkOrder(ctx context.Context, arg CreateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, createWorkOrder,
		arg.ClientID,
		arg.DeviceID,
		arg.ServiceType,
		arg.ReportedIssue,
		arg.IntakeNotes,
		arg.Accessories,
		arg.DevicePinEncrypted,
		arg.CreatedByUserID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WoNumber,
		&i.DeviceID,
		&i.ClientID,
		&i.ServiceType,
		&i.Status,
		&i.ReportedIssue,
		&i.Diagnosis,
		&i.QuoteAmount,
		&i.QuoteCurrency,
		&i.QuoteSentTs,
		&i.QuoteApprovedTs,
		&i.QuoteRejectedTs,
		&i.FinalAmount,
		&i.LaborAmount,
		&i.PartsAmount,
		&i.IntakeNotes,
		&i.Accessories,
		&i.DevicePinEncrypted,
		&i.ReceivedTs,
		&i.StartedTs,
		&i.ReadyTs,
		&i.DeliveredTs,
		&i.CancelledTs,
		&i.CancelReason,
	)
	return i, err
}

const getWorkOrderByUcode = `-- name: GetWorkOrderByUcode :one
SELECT
  wo.id, wo.ucode, wo.created_ts, wo.created_by_user_id, wo.voided_ts, wo.voided_by_user_id, wo.wo_number, wo.device_id, wo.client_id, wo.service_type, wo.status, wo.reported_issue, wo.diagnosis, wo.quote_amount, wo.quote_currency, wo.quote_sent_ts, wo.quote_approved_ts, wo.quote_rejected_ts, wo.final_amount, wo.labor_amount, wo.parts_amount, wo.intake_notes, wo.accessories, wo.device_pin_encrypted, wo.received_ts, wo.started_ts, wo.ready_ts, wo.delivered_ts, wo.cancelled_ts, wo.cancel_reason,
  c.ucode  AS client_ucode,
  c.name   AS client_name,
  c.phone  AS client_phone,
  d.ucode  AS device_ucode,
  b.ucode  AS brand_ucode,
  b.name   AS brand_name,
  dm.ucode AS model_ucode,
  dm.name  AS model_name,
  at.ucode AS article_type_ucode,
  at.name  AS article_type_name,
  d.serial_number AS device_serial
FROM rp.work_orders wo
JOIN rp.clients c       ON c.id = wo.client_id
JOIN rp.devices d       ON d.id = wo.device_id
JOIN rp.brands b        ON b.id = d.brand_id
LEFT JOIN rp.device_models dm ON dm.id = d.model_id
JOIN rp.article_types at      ON at.id = d.article_type_id
WHERE wo.ucode = $1
  AND wo.voided_ts IS NULL
`

type GetWorkOrderByUcodeRow struct {
	WorkOrder        WorkOrder   `json:"work_order"`
	ClientUcode      pgtype.UUID `json:"client_ucode"`
	ClientName       string      `json:"client_name"`
	ClientPhone      pgtype.Text `json:"client_phone"`
	DeviceUcode      pgtype.UUID `json:"device_ucode"`
	BrandUcode       pgtype.UUID `json:"brand_ucode"`
	BrandName        string      `json:"brand_name"`
	ModelUcode       pgtype.UUID `json:"model_ucode"`
	ModelName        pgtype.Text `json:"model_name"`
	ArticleTypeUcode pgtype.UUID `json:"article_type_ucode"`
	ArticleTypeName  string      `json:"article_type_name"`
	DeviceSerial     pgtype.Text `json:"device_serial"`
}

func (q *Queries) GetWorkOrderByUcode(ctx context.Context, ucode pgtype.UUID) (GetWorkOrderByUcodeRow, error) {
	row := q.db.QueryRow(ctx, getWorkOrderByUcode, ucode)
	var i GetWorkOrderByUcodeRow
	err := row.Scan(
		&i.WorkOrder.ID,
		&i.WorkOrder.Ucode,
		&i.WorkOrder.CreatedTs,
		&i.WorkOrder.CreatedByUserID,
		&i.WorkOrder.VoidedTs,
		&i.WorkOrder.VoidedByUserID,
		&i.WorkOrder.WoNumber,
		&i.WorkOrder.DeviceID,
		&i.WorkOrder.ClientID,
		&i.WorkOrder.ServiceType,
		&i.WorkOrder.Status,
		&i.WorkOrder.ReportedIssue,
		&i.WorkOrder.Diagnosis,
		&i.WorkOrder.QuoteAmount,
		&i.WorkOrder.QuoteCurrency,
		&i.WorkOrder.QuoteSentTs,
		&i.WorkOrder.QuoteApprovedTs,
		&i.WorkOrder.QuoteRejectedTs,
		&i.WorkOrder.FinalAmount,
		&i.WorkOrder.LaborAmount,
		&i.WorkOrder.PartsAmount,
		&i.WorkOrder.IntakeNotes,
		&i.WorkOrder.Accessories,
		&i.WorkOrder.DevicePinEncrypted,
		&i.WorkOrder.ReceivedTs,
		&i.WorkOrder.StartedTs,
		&i.WorkOrder.ReadyTs,
		&i.WorkOrder.DeliveredTs,
		&i.WorkOrder.CancelledTs,
		&i.WorkOrder.CancelReason,
		&i.ClientUcode,
		&i.ClientName,
		&i.ClientPhone,
		&i.DeviceUcode,
		&i.BrandUcode,
		&i.BrandName,
		&i.ModelUcode,
		&i.ModelName,
		&i.ArticleTypeUcode,
		&i.ArticleTypeName,
		&i.DeviceSerial,
	)
	return i, err
}

const listWorkOrders = `-- name: ListWorkOrders :many
SELECT
  wo.id, wo.ucode, wo.created_ts, wo.created_by_user_id, wo.voided_ts, wo.voided_by_user_id, wo.wo_number, wo.device_id, wo.client_id, wo.service_type, wo.status, wo.reported_issue, wo.diagnosis, wo.quote_amount, wo.quote_currency, wo.quote_sent_ts, wo.quote_approved_ts, wo.quote_rejected_ts, wo.final_amount, wo.labor_amount, wo.parts_amount, wo.intake_notes, wo.accessories, wo.device_pin_encrypted, wo.received_ts, wo.started_ts, wo.ready_ts, wo.delivered_ts, wo.cancelled_ts, wo.cancel_reason,
  c.ucode AS client_ucode,
  c.name AS client_name,
  c.phone AS client_phone,
  d.ucode AS device_ucode,
  b.name AS brand_name,
  dm.name AS model_name,
  at.name AS article_type_name
FROM rp.work_orders wo
JOIN rp.clients c ON c.id = wo.client_id
JOIN rp.devices d ON d.id = wo.device_id
JOIN rp.brands b ON b.id = d.brand_id
LEFT JOIN rp.device_models dm ON dm.id = d.model_id
JOIN rp.article_types at ON at.id = d.article_type_id
WHERE wo.voided_ts IS NULL
  AND ($1::text = '' OR wo.status = $1::text)
  AND (NOT $2::bool OR wo.client_id = $3::bigint)
  AND (
    $4::text = ''
    OR wo.wo_number ILIKE '%' || $4::text || '%'
    OR c.name ILIKE '%' || $4::text || '%'
    OR c.phone = $4::text
    OR d.serial_number ILIKE $4::text || '%'
  )
ORDER BY wo.received_ts DESC
LIMIT $6::int OFFSET $5::int
`

type ListWorkOrdersParams struct {
	Status     string `json:"status"`
	HasClient  bool   `json:"has_client"`
	ClientID   int64  `json:"client_id"`
	Q          string `json:"q"`
	PageOffset int32  `json:"page_offset"`
	PageSize   int32  `json:"page_size"`
}

type ListWorkOrdersRow struct {
	WorkOrder       WorkOrder   `json:"work_order"`
	ClientUcode     pgtype.UUID `json:"client_ucode"`
	ClientName      string      `json:"client_name"`
	ClientPhone     pgtype.Text `json:"client_phone"`
	DeviceUcode     pgtype.UUID `json:"device_ucode"`
	BrandName       string      `json:"brand_name"`
	ModelName       pgtype.Text `json:"model_name"`
	ArticleTypeName string      `json:"article_type_name"`
}

func (q *Queries) ListWorkOrders(ctx context.Context, arg ListWorkOrdersParams) ([]ListWorkOrdersRow, error) {
	rows, err := q.db.Query(ctx, listWorkOrders,
		arg.Status,
		arg.HasClient,
		arg.ClientID,
		arg.Q,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkOrdersRow{}
	for rows.Next() {
		var i ListWorkOrdersRow
		if err := rows.Scan(
			&i.WorkOrder.ID,
			&i.WorkOrder.Ucode,
			&i.WorkOrder.CreatedTs,
			&i.WorkOrder.CreatedByUserID,
			&i.WorkOrder.VoidedTs,
			&i.WorkOrder.VoidedByUserID,
			&i.WorkOrder.WoNumber,
			&i.WorkOrder.DeviceID,
			&i.WorkOrder.ClientID,
			&i.WorkOrder.ServiceType,
			&i.WorkOrder.Status,
			&i.WorkOrder.ReportedIssue,
			&i.WorkOrder.Diagnosis,
			&i.WorkOrder.QuoteAmount,
			&i.WorkOrder.QuoteCurrency,
			&i.WorkOrder.QuoteSentTs,
			&i.WorkOrder.QuoteApprovedTs,
			&i.WorkOrder.QuoteRejectedTs,
			&i.WorkOrder.FinalAmount,
			&i.WorkOrder.LaborAmount,
			&i.WorkOrder.PartsAmount,
			&i.WorkOrder.IntakeNotes,
			&i.WorkOrder.Accessories,
			&i.WorkOrder.DevicePinEncrypted,
			&i.WorkOrder.ReceivedTs,
			&i.WorkOrder.StartedTs,
			&i.WorkOrder.ReadyTs,
			&i.WorkOrder.DeliveredTs,
			&i.WorkOrder.CancelledTs,
			&i.WorkOrder.CancelReason,
			&i.ClientUcode,
			&i.ClientName,
			&i.ClientPhone,
			&i.DeviceUcode,
			&i.BrandName,
			&i.ModelName,
			&i.ArticleTypeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkOrderFinals = `-- name: SetWorkOrderFinals :one
UPDATE rp.work_orders
SET
  status = 'ready',
  diagnosis = COALESCE($2, diagnosis),
  labor_amount = COALESCE($3, labor_amount),
  parts_amount = COALESCE($4, parts_amount),
  final_amount = COALESCE($5, final_amount),
  ready_ts = COALESCE(ready_ts, now())
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, wo_number, device_id, client_id, service_type, status, reported_issue, diagnosis, quote_amount, quote_currency, quote_sent_ts, quote_approved_ts, quote_rejected_ts, final_amount, labor_amount, parts_amount, intake_notes, accessories, device_pin_encrypted, received_ts, started_ts, ready_ts, delivered_ts, cancelled_ts, cancel_reason
`

type SetWorkOrderFinalsParams struct {
	ID          int64          `json:"id"`
	Diagnosis   pgtype.Text    `json:"diagnosis"`
	LaborAmount pgtype.Numeric `json:"labor_amount"`
	PartsAmount pgtype.Numeric `json:"parts_amount"`
	FinalAmount pgtype.Numeric `json:"final_amount"`
}

func (q *Queries) SetWorkOrderFinals(ctx context.Context, arg SetWorkOrderFinalsParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, setWorkOrderFinals,
		arg.ID,
		arg.Diagnosis,
		arg.LaborAmount,
		arg.PartsAmount,
		arg.FinalAmount,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WoNumber,
		&i.DeviceID,
		&i.ClientID,
		&i.ServiceType,
		&i.Status,
		&i.ReportedIssue,
		&i.Diagnosis,
		&i.QuoteAmount,
		&i.QuoteCurrency,
		&i.QuoteSentTs,
		&i.QuoteApprovedTs,
		&i.QuoteRejectedTs,
		&i.FinalAmount,
		&i.LaborAmount,
		&i.PartsAmount,
		&i.IntakeNotes,
		&i.Accessories,
		&i.DevicePinEncrypted,
		&i.ReceivedTs,
		&i.StartedTs,
		&i.ReadyTs,
		&i.DeliveredTs,
		&i.CancelledTs,
		&i.CancelReason,
	)
	return i, err
}

const setWorkOrderQuote = `-- name: SetWorkOrderQuote :one
UPDATE rp.work_orders
SET
  status = 'quoted',
  diagnosis = COALESCE($2, diagnosis),
  quote_amount = $3,
  quote_currency = COALESCE($4::text, quote_currency)::char(3),
  quote_sent_ts = now()
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, wo_number, device_id, client_id, service_type, status, reported_issue, diagnosis, quote_amount, quote_currency, quote_sent_ts, quote_approved_ts, quote_rejected_ts, final_amount, labor_amount, parts_amount, intake_notes, accessories, device_pin_encrypted, received_ts, started_ts, ready_ts, delivered_ts, cancelled_ts, cancel_reason
`

type SetWorkOrderQuoteParams struct {
	ID            int64          `json:"id"`
	Diagnosis     pgtype.Text    `json:"diagnosis"`
	QuoteAmount   pgtype.Numeric `json:"quote_amount"`
	QuoteCurrency pgtype.Text    `json:"quote_currency"`
}

func (q *Queries) SetWorkOrderQuote(ctx context.Context, arg SetWorkOrderQuoteParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, setWorkOrderQuote,
		arg.ID,
		arg.Diagnosis,
		arg.QuoteAmount,
		arg.QuoteCurrency,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WoNumber,
		&i.DeviceID,
		&i.ClientID,
		&i.ServiceType,
		&i.Status,
		&i.ReportedIssue,
		&i.Diagnosis,
		&i.QuoteAmount,
		&i.QuoteCurrency,
		&i.QuoteSentTs,
		&i.QuoteApprovedTs,
		&i.QuoteRejectedTs,
		&i.FinalAmount,
		&i.LaborAmount,
		&i.PartsAmount,
		&i.IntakeNotes,
		&i.Accessories,
		&i.DevicePinEncrypted,
		&i.ReceivedTs,
		&i.StartedTs,
		&i.ReadyTs,
		&i.DeliveredTs,
		&i.CancelledTs,
		&i.CancelReason,
	)
	return i, err
}

const setWorkOrderQuoteOutcome = `-- name: SetWorkOrderQuoteOutcome :one
UPDATE rp.work_orders
SET
  status = $2,
  quote_approved_ts = CASE WHEN $2 = 'approved' THEN now() ELSE quote_approved_ts END,
  quote_rejected_ts = CASE WHEN $2 = 'rejected' THEN now() ELSE quote_rejected_ts END
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, wo_number, device_id, client_id, service_type, status, reported_issue, diagnosis, quote_amount, quote_currency, quote_sent_ts, quote_approved_ts, quote_rejected_ts, final_amount, labor_amount, parts_amount, intake_notes, accessories, device_pin_encrypted, received_ts, started_ts, ready_ts, delivered_ts, cancelled_ts, cancel_reason
`

type SetWorkOrderQuoteOutcomeParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetWorkOrderQuoteOutcome(ctx context.Context, arg SetWorkOrderQuoteOutcomeParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, setWorkOrderQuoteOutcome, arg.ID, arg.Status)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WoNumber,
		&i.DeviceID,
		&i.ClientID,
		&i.ServiceType,
		&i.Status,
		&i.ReportedIssue,
		&i.Diagnosis,
		&i.QuoteAmount,
		&i.QuoteCurrency,
		&i.QuoteSentTs,
		&i.QuoteApprovedTs,
		&i.QuoteRejectedTs,
		&i.FinalAmount,
		&i.LaborAmount,
		&i.PartsAmount,
		&i.IntakeNotes,
		&i.Accessories,
		&i.DevicePinEncrypted,
		&i.ReceivedTs,
		&i.StartedTs,
		&i.ReadyTs,
		&i.DeliveredTs,
		&i.CancelledTs,
		&i.CancelReason,
	)
	return i, err
}

const softDeleteWorkOrder = `-- name: SoftDeleteWorkOrder :exec
UPDATE rp.work_orders
SET
  voided_ts = now(),
  voided_by_user_id = $2
WHERE id = $1
  AND voided_ts IS NULL
`

type SoftDeleteWorkOrderParams struct {
	ID             int64       `json:"id"`
	VoidedByUserID pgtype.Int8 `json:"voided_by_user_id"`
}

func (q *Queries) SoftDeleteWorkOrder(ctx context.Context, arg SoftDeleteWorkOrderParams) error {
	_, err := q.db.Exec(ctx, softDeleteWorkOrder, arg.ID, arg.VoidedByUserID)
	return err
}

const updateWorkOrderFields = `-- name: UpdateWorkOrderFields :one
UPDATE rp.work_orders
SET
  service_type = $2,
  reported_issue = $3,
  diagnosis = $4,
  intake_notes = $5,
  accessories = $6,
  device_pin_encrypted = $7
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, wo_number, device_id, client_id, service_type, status, reported_issue, diagnosis, quote_amount, quote_currency, quote_sent_ts, quote_approved_ts, quote_rejected_ts, final_amount, labor_amount, parts_amount, intake_notes, accessories, device_pin_encrypted, received_ts, started_ts, ready_ts, delivered_ts, cancelled_ts, cancel_reason
`

type UpdateWorkOrderFieldsParams struct {
	ID                 int64       `json:"id"`
	ServiceType        string      `json:"service_type"`
	ReportedIssue      string      `json:"reported_issue"`
	Diagnosis          pgtype.Text `json:"diagnosis"`
	IntakeNotes        pgtype.Text `json:"intake_notes"`
	Accessories        pgtype.Text `json:"accessories"`
	DevicePinEncrypted pgtype.Text `json:"device_pin_encrypted"`
}

func (q *Queries) UpdateWorkOrderFields(ctx context.Context, arg UpdateWorkOrderFieldsParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderFields,
		arg.ID,
		arg.ServiceType,
		arg.ReportedIssue,
		arg.Diagnosis,
		arg.IntakeNotes,
		arg.Accessories,
		arg.DevicePinEncrypted,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WoNumber,
		&i.DeviceID,
		&i.ClientID,
		&i.ServiceType,
		&i.Status,
		&i.ReportedIssue,
		&i.Diagnosis,
		&i.QuoteAmount,
		&i.QuoteCurrency,
		&i.QuoteSentTs,
		&i.QuoteApprovedTs,
		&i.QuoteRejectedTs,
		&i.FinalAmount,
		&i.LaborAmount,
		&i.PartsAmount,
		&i.IntakeNotes,
		&i.Accessories,
		&i.DevicePinEncrypted,
		&i.ReceivedTs,
		&i.StartedTs,
		&i.ReadyTs,
		&i.DeliveredTs,
		&i.CancelledTs,
		&i.CancelReason,
	)
	return i, err
}

const updateWorkOrderStatus = `-- name: UpdateWorkOrderStatus :one
UPDATE rp.work_orders
SET
  status = $2,
  started_ts = COALESCE(started_ts, CASE WHEN $2 = 'in_repair' THEN now() END),
  ready_ts = COALESCE(ready_ts, CASE WHEN $2 = 'ready' THEN now() END),
  delivered_ts = COALESCE(delivered_ts, CASE WHEN $2 = 'delivered' THEN now() END),
  cancelled_ts = COALESCE(cancelled_ts, CASE WHEN $2 = 'cancelled' THEN now() END),
  cancel_reason = COALESCE($3, cancel_reason)
WHERE id = $1
  AND voided_ts IS NULL
RETURNING id, ucode, created_ts, created_by_user_id, voided_ts, voided_by_user_id, wo_number, device_id, client_id, service_type, status, reported_issue, diagnosis, quote_amount, quote_currency, quote_sent_ts, quote_approved_ts, quote_rejected_ts, final_amount, labor_amount, parts_amount, intake_notes, accessories, device_pin_encrypted, received_ts, started_ts, ready_ts, delivered_ts, cancelled_ts, cancel_reason
`

type UpdateWorkOrderStatusParams struct {
	ID           int64       `json:"id"`
	Status       string      `json:"status"`
	CancelReason pgtype.Text `json:"cancel_reason"`
}

func (q *Queries) UpdateWorkOrderStatus(ctx context.Context, arg UpdateWorkOrderStatusParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrderStatus, arg.ID, arg.Status, arg.CancelReason)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.Ucode,
		&i.CreatedTs,
		&i.CreatedByUserID,
		&i.VoidedTs,
		&i.VoidedByUserID,
		&i.WoNumber,
		&i.DeviceID,
		&i.ClientID,
		&i.ServiceType,
		&i.Status,
		&i.ReportedIssue,
		&i.Diagnosis,
		&i.QuoteAmount,
		&i.QuoteCurrency,
		&i.QuoteSentTs,
		&i.QuoteApprovedTs,
		&i.QuoteRejectedTs,
		&i.FinalAmount,
		&i.LaborAmount,
		&i.PartsAmount,
		&i.IntakeNotes,
		&i.Accessories,
		&i.DevicePinEncrypted,
		&i.ReceivedTs,
		&i.StartedTs,
		&i.ReadyTs,
		&i.DeliveredTs,
		&i.CancelledTs,
		&i.CancelReason,
	)
	return i, err
}
